#!/usr/bin/env python3
"""Regenerate the Score Summary table in BestPracticesChecklist.md from its checkboxes.

The checklist marks each criterion with one of three states:

    - [x] ...   met
    - [ ] ...   not met
    - [~] ...   N/A or partial, with a justification

`[~]` rows are excluded from the percentage rather than counted as failures, so a
criterion that genuinely does not apply (the crypto rows, for example) cannot drag
the score down. They are still reported in their own column so nothing is hidden.

Usage:
    python .github/scripts/checklist_score.py            # rewrite the table in place
    python .github/scripts/checklist_score.py --check    # report drift, change nothing

Exit codes:
    0  table is up to date, or was rewritten
    1  the file is malformed (missing markers, or no criteria found)
    2  --check only: the table is out of date
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_FILE = Path("BestPracticesChecklist.md")

START_MARKER = "<!-- checklist-score:start -->"
END_MARKER = "<!-- checklist-score:end -->"

SECTION_RE = re.compile(r"^##\s+(?P<name>.*\S)\s*$")
CRITERION_RE = re.compile(r"^\s*-\s*\[(?P<state>[ xX~])\]")
LEADING_NON_WORD_RE = re.compile(r"^[^\w]+", re.UNICODE)

# Headings that are prose, not criteria. Compared case-insensitively after emoji is stripped.
EXCLUDED_SECTIONS = {"score summary", "project-specific notes"}

# Percentage thresholds for the Status column.
GREEN, YELLOW = 100, 50


class Section:
    def __init__(self, name: str) -> None:
        self.name = name
        self.met = 0
        self.unmet = 0
        self.na = 0

    @property
    def total(self) -> int:
        return self.met + self.unmet + self.na

    @property
    def applicable(self) -> int:
        """Criteria the score is actually measured against."""
        return self.met + self.unmet

    @property
    def percent(self) -> int | None:
        if self.applicable == 0:
            return None
        return round(self.met * 100 / self.applicable)

    @property
    def status(self) -> str:
        pct = self.percent
        if pct is None:
            return "⚪"
        if pct >= GREEN:
            return "🟢"
        if pct >= YELLOW:
            return "🟡"
        return "🔴"


def clean_heading(name: str) -> str:
    """'🏗️ Basics' -> 'Basics'."""
    return LEADING_NON_WORD_RE.sub("", name).strip()


def parse(lines: list[str]) -> list[Section]:
    sections: list[Section] = []
    current: Section | None = None

    for line in lines:
        heading = SECTION_RE.match(line)
        if heading:
            name = clean_heading(heading.group("name"))
            current = None if name.lower() in EXCLUDED_SECTIONS else Section(name)
            if current is not None:
                sections.append(current)
            continue

        criterion = CRITERION_RE.match(line)
        if criterion is None or current is None:
            continue

        state = criterion.group("state").lower()
        if state == "x":
            current.met += 1
        elif state == "~":
            current.na += 1
        else:
            current.unmet += 1

    # Drop prose sections that happened to contain no criteria at all.
    return [s for s in sections if s.total > 0]


def render(sections: list[Section]) -> str:
    grand = Section("**Total**")
    for s in sections:
        grand.met += s.met
        grand.unmet += s.unmet
        grand.na += s.na

    rows = [
        (s.name, str(s.met), str(s.na), str(s.total), s.status) for s in sections
    ]
    rows.append(
        (
            grand.name,
            f"**{grand.met}**",
            f"**{grand.na}**",
            f"**{grand.total}**",
            f"**{grand.percent if grand.percent is not None else 0}%**",
        )
    )

    headers = ("Category", "Met", "N/A", "Total", "Status")
    widths = [
        max(len(h), *(len(row[i]) for row in rows)) for i, h in enumerate(headers)
    ]

    def line(cells: tuple[str, ...]) -> str:
        return "| " + " | ".join(c.ljust(w) for c, w in zip(cells, widths)) + " |"

    out = [
        START_MARKER,
        "<!-- Generated by .github/workflows/checklist-score.yml — do not edit by hand -->",
        line(headers),
        "|" + "|".join("-" * (w + 2) for w in widths) + "|",
        *(line(r) for r in rows),
        "",
        f"_{grand.met} of {grand.applicable} applicable criteria met "
        f"({grand.na} marked N/A, {grand.total} total)._",
        END_MARKER,
    ]
    return "\n".join(out)


def splice(text: str, table: str) -> str:
    start = text.find(START_MARKER)
    end = text.find(END_MARKER)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(
            f"error: could not find {START_MARKER} / {END_MARKER} in the checklist.\n"
            "Add both marker comments around the Score Summary table."
        )
    return text[:start] + table + text[end + len(END_MARKER):]


def main() -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift, change nothing")
    parser.add_argument("--file", type=Path, default=DEFAULT_FILE, help="checklist path")
    args = parser.parse_args()

    if not args.file.is_file():
        print(f"error: {args.file} not found", file=sys.stderr)
        return 1

    original = args.file.read_text(encoding="utf-8")
    sections = parse(original.splitlines())
    if not sections:
        print(f"error: no '- [x]' style criteria found in {args.file}", file=sys.stderr)
        return 1

    updated = splice(original, render(sections))

    if updated == original:
        print(f"{args.file}: score table is up to date.")
        return 0

    if args.check:
        print(f"::warning file={args.file}::Score summary is out of date; "
              f"run `python .github/scripts/checklist_score.py` to refresh it.")
        print("\nExpected:\n")
        print(render(sections))
        return 2

    args.file.write_text(updated, encoding="utf-8", newline="\n")
    print(f"{args.file}: score table updated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
