// Mocks generated by Mockito 5.4.6 from annotations
// in resonate/test/controllers/change_email_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:appwrite/appwrite.dart' as _i4;
import 'package:appwrite/enums.dart' as _i6;
import 'package:appwrite/models.dart' as _i3;
import 'package:appwrite/src/client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionList_1 extends _i1.SmartFake
    implements _i3.TransactionList {
  _FakeTransactionList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_2 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRowList_3 extends _i1.SmartFake implements _i3.RowList {
  _FakeRowList_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRow_4 extends _i1.SmartFake implements _i3.Row {
  _FakeRow_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_5 extends _i1.SmartFake implements _i3.User {
  _FakeUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdentityList_6 extends _i1.SmartFake implements _i3.IdentityList {
  _FakeIdentityList_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJwt_7 extends _i1.SmartFake implements _i3.Jwt {
  _FakeJwt_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogList_8 extends _i1.SmartFake implements _i3.LogList {
  _FakeLogList_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaType_9 extends _i1.SmartFake implements _i3.MfaType {
  _FakeMfaType_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaChallenge_10 extends _i1.SmartFake implements _i3.MfaChallenge {
  _FakeMfaChallenge_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_11 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaFactors_12 extends _i1.SmartFake implements _i3.MfaFactors {
  _FakeMfaFactors_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaRecoveryCodes_13 extends _i1.SmartFake
    implements _i3.MfaRecoveryCodes {
  _FakeMfaRecoveryCodes_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePreferences_14 extends _i1.SmartFake implements _i3.Preferences {
  _FakePreferences_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeToken_15 extends _i1.SmartFake implements _i3.Token {
  _FakeToken_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionList_16 extends _i1.SmartFake implements _i3.SessionList {
  _FakeSessionList_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTarget_17 extends _i1.SmartFake implements _i3.Target {
  _FakeTarget_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TablesDB].
///
/// See the documentation for Mockito's code generation for more information.
class MockTablesDB extends _i1.Mock implements _i4.TablesDB {
  MockTablesDB() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<_i3.TransactionList> listTransactions({List<String>? queries}) =>
      (super.noSuchMethod(
            Invocation.method(#listTransactions, [], {#queries: queries}),
            returnValue: _i5.Future<_i3.TransactionList>.value(
              _FakeTransactionList_1(
                this,
                Invocation.method(#listTransactions, [], {#queries: queries}),
              ),
            ),
          )
          as _i5.Future<_i3.TransactionList>);

  @override
  _i5.Future<_i3.Transaction> createTransaction({int? ttl}) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {#ttl: ttl}),
            returnValue: _i5.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createTransaction, [], {#ttl: ttl}),
              ),
            ),
          )
          as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<_i3.Transaction> getTransaction({
    required String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#getTransaction, [], {
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<_i3.Transaction> updateTransaction({
    required String? transactionId,
    bool? commit,
    bool? rollback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [], {
              #transactionId: transactionId,
              #commit: commit,
              #rollback: rollback,
            }),
            returnValue: _i5.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#updateTransaction, [], {
                  #transactionId: transactionId,
                  #commit: commit,
                  #rollback: rollback,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<dynamic> deleteTransaction({required String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Transaction> createOperations({
    required String? transactionId,
    List<Map<dynamic, dynamic>>? operations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOperations, [], {
              #transactionId: transactionId,
              #operations: operations,
            }),
            returnValue: _i5.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createOperations, [], {
                  #transactionId: transactionId,
                  #operations: operations,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<_i3.RowList> listRows({
    required String? databaseId,
    required String? tableId,
    List<String>? queries,
    String? transactionId,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listRows, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #queries: queries,
              #transactionId: transactionId,
              #total: total,
            }),
            returnValue: _i5.Future<_i3.RowList>.value(
              _FakeRowList_3(
                this,
                Invocation.method(#listRows, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #queries: queries,
                  #transactionId: transactionId,
                  #total: total,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.RowList>);

  @override
  _i5.Future<_i3.Row> createRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#createRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<_i3.Row> getRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    List<String>? queries,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #queries: queries,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#getRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #queries: queries,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<_i3.Row> upsertRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#upsertRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<_i3.Row> updateRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#updateRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<dynamic> deleteRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Row> decrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? min,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #min: min,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#decrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #min: min,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<_i3.Row> incrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? max,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #max: max,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#incrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #max: max,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);
}

/// A class which mocks [Account].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccount extends _i1.Mock implements _i4.Account {
  MockAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<_i3.User> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(this, Invocation.method(#get, [])),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.User> create({
    required String? userId,
    required String? email,
    required String? password,
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #userId: userId,
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#create, [], {
                  #userId: userId,
                  #email: email,
                  #password: password,
                  #name: name,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.User> updateEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#updateEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.IdentityList> listIdentities({
    List<String>? queries,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listIdentities, [], {
              #queries: queries,
              #total: total,
            }),
            returnValue: _i5.Future<_i3.IdentityList>.value(
              _FakeIdentityList_6(
                this,
                Invocation.method(#listIdentities, [], {
                  #queries: queries,
                  #total: total,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.IdentityList>);

  @override
  _i5.Future<dynamic> deleteIdentity({required String? identityId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIdentity, [], {#identityId: identityId}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Jwt> createJWT() =>
      (super.noSuchMethod(
            Invocation.method(#createJWT, []),
            returnValue: _i5.Future<_i3.Jwt>.value(
              _FakeJwt_7(this, Invocation.method(#createJWT, [])),
            ),
          )
          as _i5.Future<_i3.Jwt>);

  @override
  _i5.Future<_i3.LogList> listLogs({List<String>? queries, bool? total}) =>
      (super.noSuchMethod(
            Invocation.method(#listLogs, [], {
              #queries: queries,
              #total: total,
            }),
            returnValue: _i5.Future<_i3.LogList>.value(
              _FakeLogList_8(
                this,
                Invocation.method(#listLogs, [], {
                  #queries: queries,
                  #total: total,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.LogList>);

  @override
  _i5.Future<_i3.User> updateMFA({required bool? mfa}) =>
      (super.noSuchMethod(
            Invocation.method(#updateMFA, [], {#mfa: mfa}),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(this, Invocation.method(#updateMFA, [], {#mfa: mfa})),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.MfaType> createMfaAuthenticator({
    required _i6.AuthenticatorType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMfaAuthenticator, [], {#type: type}),
            returnValue: _i5.Future<_i3.MfaType>.value(
              _FakeMfaType_9(
                this,
                Invocation.method(#createMfaAuthenticator, [], {#type: type}),
              ),
            ),
          )
          as _i5.Future<_i3.MfaType>);

  @override
  _i5.Future<_i3.MfaType> createMFAAuthenticator({
    required _i6.AuthenticatorType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMFAAuthenticator, [], {#type: type}),
            returnValue: _i5.Future<_i3.MfaType>.value(
              _FakeMfaType_9(
                this,
                Invocation.method(#createMFAAuthenticator, [], {#type: type}),
              ),
            ),
          )
          as _i5.Future<_i3.MfaType>);

  @override
  _i5.Future<_i3.User> updateMfaAuthenticator({
    required _i6.AuthenticatorType? type,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMfaAuthenticator, [], {
              #type: type,
              #otp: otp,
            }),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#updateMfaAuthenticator, [], {
                  #type: type,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.User> updateMFAAuthenticator({
    required _i6.AuthenticatorType? type,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMFAAuthenticator, [], {
              #type: type,
              #otp: otp,
            }),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#updateMFAAuthenticator, [], {
                  #type: type,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<dynamic> deleteMfaAuthenticator({
    required _i6.AuthenticatorType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMfaAuthenticator, [], {#type: type}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> deleteMFAAuthenticator({
    required _i6.AuthenticatorType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMFAAuthenticator, [], {#type: type}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.MfaChallenge> createMfaChallenge({
    required _i6.AuthenticationFactor? factor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMfaChallenge, [], {#factor: factor}),
            returnValue: _i5.Future<_i3.MfaChallenge>.value(
              _FakeMfaChallenge_10(
                this,
                Invocation.method(#createMfaChallenge, [], {#factor: factor}),
              ),
            ),
          )
          as _i5.Future<_i3.MfaChallenge>);

  @override
  _i5.Future<_i3.MfaChallenge> createMFAChallenge({
    required _i6.AuthenticationFactor? factor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMFAChallenge, [], {#factor: factor}),
            returnValue: _i5.Future<_i3.MfaChallenge>.value(
              _FakeMfaChallenge_10(
                this,
                Invocation.method(#createMFAChallenge, [], {#factor: factor}),
              ),
            ),
          )
          as _i5.Future<_i3.MfaChallenge>);

  @override
  _i5.Future<_i3.Session> updateMfaChallenge({
    required String? challengeId,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMfaChallenge, [], {
              #challengeId: challengeId,
              #otp: otp,
            }),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#updateMfaChallenge, [], {
                  #challengeId: challengeId,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<_i3.Session> updateMFAChallenge({
    required String? challengeId,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMFAChallenge, [], {
              #challengeId: challengeId,
              #otp: otp,
            }),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#updateMFAChallenge, [], {
                  #challengeId: challengeId,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<_i3.MfaFactors> listMfaFactors() =>
      (super.noSuchMethod(
            Invocation.method(#listMfaFactors, []),
            returnValue: _i5.Future<_i3.MfaFactors>.value(
              _FakeMfaFactors_12(this, Invocation.method(#listMfaFactors, [])),
            ),
          )
          as _i5.Future<_i3.MfaFactors>);

  @override
  _i5.Future<_i3.MfaFactors> listMFAFactors() =>
      (super.noSuchMethod(
            Invocation.method(#listMFAFactors, []),
            returnValue: _i5.Future<_i3.MfaFactors>.value(
              _FakeMfaFactors_12(this, Invocation.method(#listMFAFactors, [])),
            ),
          )
          as _i5.Future<_i3.MfaFactors>);

  @override
  _i5.Future<_i3.MfaRecoveryCodes> getMfaRecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#getMfaRecoveryCodes, []),
            returnValue: _i5.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_13(
                this,
                Invocation.method(#getMfaRecoveryCodes, []),
              ),
            ),
          )
          as _i5.Future<_i3.MfaRecoveryCodes>);

  @override
  _i5.Future<_i3.MfaRecoveryCodes> getMFARecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#getMFARecoveryCodes, []),
            returnValue: _i5.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_13(
                this,
                Invocation.method(#getMFARecoveryCodes, []),
              ),
            ),
          )
          as _i5.Future<_i3.MfaRecoveryCodes>);

  @override
  _i5.Future<_i3.MfaRecoveryCodes> createMfaRecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#createMfaRecoveryCodes, []),
            returnValue: _i5.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_13(
                this,
                Invocation.method(#createMfaRecoveryCodes, []),
              ),
            ),
          )
          as _i5.Future<_i3.MfaRecoveryCodes>);

  @override
  _i5.Future<_i3.MfaRecoveryCodes> createMFARecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#createMFARecoveryCodes, []),
            returnValue: _i5.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_13(
                this,
                Invocation.method(#createMFARecoveryCodes, []),
              ),
            ),
          )
          as _i5.Future<_i3.MfaRecoveryCodes>);

  @override
  _i5.Future<_i3.MfaRecoveryCodes> updateMfaRecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#updateMfaRecoveryCodes, []),
            returnValue: _i5.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_13(
                this,
                Invocation.method(#updateMfaRecoveryCodes, []),
              ),
            ),
          )
          as _i5.Future<_i3.MfaRecoveryCodes>);

  @override
  _i5.Future<_i3.MfaRecoveryCodes> updateMFARecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#updateMFARecoveryCodes, []),
            returnValue: _i5.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_13(
                this,
                Invocation.method(#updateMFARecoveryCodes, []),
              ),
            ),
          )
          as _i5.Future<_i3.MfaRecoveryCodes>);

  @override
  _i5.Future<_i3.User> updateName({required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [], {#name: name}),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#updateName, [], {#name: name}),
              ),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.User> updatePassword({
    required String? password,
    String? oldPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #password: password,
              #oldPassword: oldPassword,
            }),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#updatePassword, [], {
                  #password: password,
                  #oldPassword: oldPassword,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.User> updatePhone({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhone, [], {
              #phone: phone,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#updatePhone, [], {
                  #phone: phone,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.Preferences> getPrefs() =>
      (super.noSuchMethod(
            Invocation.method(#getPrefs, []),
            returnValue: _i5.Future<_i3.Preferences>.value(
              _FakePreferences_14(this, Invocation.method(#getPrefs, [])),
            ),
          )
          as _i5.Future<_i3.Preferences>);

  @override
  _i5.Future<_i3.User> updatePrefs({required Map<dynamic, dynamic>? prefs}) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrefs, [], {#prefs: prefs}),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(
                this,
                Invocation.method(#updatePrefs, [], {#prefs: prefs}),
              ),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.Token> createRecovery({
    required String? email,
    required String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRecovery, [], {#email: email, #url: url}),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#createRecovery, [], {
                  #email: email,
                  #url: url,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.Token> updateRecovery({
    required String? userId,
    required String? secret,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecovery, [], {
              #userId: userId,
              #secret: secret,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#updateRecovery, [], {
                  #userId: userId,
                  #secret: secret,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.SessionList> listSessions() =>
      (super.noSuchMethod(
            Invocation.method(#listSessions, []),
            returnValue: _i5.Future<_i3.SessionList>.value(
              _FakeSessionList_16(this, Invocation.method(#listSessions, [])),
            ),
          )
          as _i5.Future<_i3.SessionList>);

  @override
  _i5.Future<dynamic> deleteSessions() =>
      (super.noSuchMethod(
            Invocation.method(#deleteSessions, []),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Session> createAnonymousSession() =>
      (super.noSuchMethod(
            Invocation.method(#createAnonymousSession, []),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#createAnonymousSession, []),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<_i3.Session> createEmailPasswordSession({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmailPasswordSession, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#createEmailPasswordSession, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<_i3.Session> updateMagicURLSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMagicURLSession, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#updateMagicURLSession, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<dynamic> createOAuth2Session({
    required _i6.OAuthProvider? provider,
    String? success,
    String? failure,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOAuth2Session, [], {
              #provider: provider,
              #success: success,
              #failure: failure,
              #scopes: scopes,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Session> updatePhoneSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneSession, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#updatePhoneSession, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<_i3.Session> createSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#createSession, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<_i3.Session> getSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [], {#sessionId: sessionId}),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#getSession, [], {#sessionId: sessionId}),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<_i3.Session> updateSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [], {#sessionId: sessionId}),
            returnValue: _i5.Future<_i3.Session>.value(
              _FakeSession_11(
                this,
                Invocation.method(#updateSession, [], {#sessionId: sessionId}),
              ),
            ),
          )
          as _i5.Future<_i3.Session>);

  @override
  _i5.Future<dynamic> deleteSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [], {#sessionId: sessionId}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.User> updateStatus() =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, []),
            returnValue: _i5.Future<_i3.User>.value(
              _FakeUser_5(this, Invocation.method(#updateStatus, [])),
            ),
          )
          as _i5.Future<_i3.User>);

  @override
  _i5.Future<_i3.Target> createPushTarget({
    required String? targetId,
    required String? identifier,
    String? providerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPushTarget, [], {
              #targetId: targetId,
              #identifier: identifier,
              #providerId: providerId,
            }),
            returnValue: _i5.Future<_i3.Target>.value(
              _FakeTarget_17(
                this,
                Invocation.method(#createPushTarget, [], {
                  #targetId: targetId,
                  #identifier: identifier,
                  #providerId: providerId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Target>);

  @override
  _i5.Future<_i3.Target> updatePushTarget({
    required String? targetId,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePushTarget, [], {
              #targetId: targetId,
              #identifier: identifier,
            }),
            returnValue: _i5.Future<_i3.Target>.value(
              _FakeTarget_17(
                this,
                Invocation.method(#updatePushTarget, [], {
                  #targetId: targetId,
                  #identifier: identifier,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Target>);

  @override
  _i5.Future<dynamic> deletePushTarget({required String? targetId}) =>
      (super.noSuchMethod(
            Invocation.method(#deletePushTarget, [], {#targetId: targetId}),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Token> createEmailToken({
    required String? userId,
    required String? email,
    bool? phrase,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmailToken, [], {
              #userId: userId,
              #email: email,
              #phrase: phrase,
            }),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#createEmailToken, [], {
                  #userId: userId,
                  #email: email,
                  #phrase: phrase,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.Token> createMagicURLToken({
    required String? userId,
    required String? email,
    String? url,
    bool? phrase,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMagicURLToken, [], {
              #userId: userId,
              #email: email,
              #url: url,
              #phrase: phrase,
            }),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#createMagicURLToken, [], {
                  #userId: userId,
                  #email: email,
                  #url: url,
                  #phrase: phrase,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<dynamic> createOAuth2Token({
    required _i6.OAuthProvider? provider,
    String? success,
    String? failure,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOAuth2Token, [], {
              #provider: provider,
              #success: success,
              #failure: failure,
              #scopes: scopes,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Token> createPhoneToken({
    required String? userId,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPhoneToken, [], {
              #userId: userId,
              #phone: phone,
            }),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#createPhoneToken, [], {
                  #userId: userId,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.Token> createEmailVerification({required String? url}) =>
      (super.noSuchMethod(
            Invocation.method(#createEmailVerification, [], {#url: url}),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#createEmailVerification, [], {#url: url}),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.Token> createVerification({required String? url}) =>
      (super.noSuchMethod(
            Invocation.method(#createVerification, [], {#url: url}),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#createVerification, [], {#url: url}),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.Token> updateEmailVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailVerification, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#updateEmailVerification, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.Token> updateVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateVerification, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#updateVerification, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.Token> createPhoneVerification() =>
      (super.noSuchMethod(
            Invocation.method(#createPhoneVerification, []),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#createPhoneVerification, []),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);

  @override
  _i5.Future<_i3.Token> updatePhoneVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneVerification, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i5.Future<_i3.Token>.value(
              _FakeToken_15(
                this,
                Invocation.method(#updatePhoneVerification, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Token>);
}
