// Mocks generated by Mockito 5.4.6 from annotations
// in resonate/test/controllers/edit_profile_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i14;

import 'package:appwrite/appwrite.dart' as _i5;
import 'package:appwrite/enums.dart' as _i10;
import 'package:appwrite/models.dart' as _i3;
import 'package:appwrite/src/client.dart' as _i2;
import 'package:appwrite/src/input_file.dart' as _i7;
import 'package:appwrite/src/upload_progress.dart' as _i8;
import 'package:get/get.dart' as _i4;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:resonate/themes/theme_controller.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionList_1 extends _i1.SmartFake
    implements _i3.TransactionList {
  _FakeTransactionList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_2 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRowList_3 extends _i1.SmartFake implements _i3.RowList {
  _FakeRowList_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRow_4 extends _i1.SmartFake implements _i3.Row {
  _FakeRow_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileList_5 extends _i1.SmartFake implements _i3.FileList {
  _FakeFileList_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_6 extends _i1.SmartFake implements _i3.File {
  _FakeFile_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_7<T> extends _i1.SmartFake implements _i4.Rx<T> {
  _FakeRx_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_8<T> extends _i1.SmartFake
    implements _i4.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TablesDB].
///
/// See the documentation for Mockito's code generation for more information.
class MockTablesDB extends _i1.Mock implements _i5.TablesDB {
  MockTablesDB() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.Future<_i3.TransactionList> listTransactions({List<String>? queries}) =>
      (super.noSuchMethod(
            Invocation.method(#listTransactions, [], {#queries: queries}),
            returnValue: _i6.Future<_i3.TransactionList>.value(
              _FakeTransactionList_1(
                this,
                Invocation.method(#listTransactions, [], {#queries: queries}),
              ),
            ),
          )
          as _i6.Future<_i3.TransactionList>);

  @override
  _i6.Future<_i3.Transaction> createTransaction({int? ttl}) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {#ttl: ttl}),
            returnValue: _i6.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createTransaction, [], {#ttl: ttl}),
              ),
            ),
          )
          as _i6.Future<_i3.Transaction>);

  @override
  _i6.Future<_i3.Transaction> getTransaction({
    required String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#getTransaction, [], {
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Transaction>);

  @override
  _i6.Future<_i3.Transaction> updateTransaction({
    required String? transactionId,
    bool? commit,
    bool? rollback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [], {
              #transactionId: transactionId,
              #commit: commit,
              #rollback: rollback,
            }),
            returnValue: _i6.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#updateTransaction, [], {
                  #transactionId: transactionId,
                  #commit: commit,
                  #rollback: rollback,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Transaction>);

  @override
  _i6.Future<dynamic> deleteTransaction({required String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.Transaction> createOperations({
    required String? transactionId,
    List<Map<dynamic, dynamic>>? operations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOperations, [], {
              #transactionId: transactionId,
              #operations: operations,
            }),
            returnValue: _i6.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createOperations, [], {
                  #transactionId: transactionId,
                  #operations: operations,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Transaction>);

  @override
  _i6.Future<_i3.RowList> listRows({
    required String? databaseId,
    required String? tableId,
    List<String>? queries,
    String? transactionId,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listRows, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #queries: queries,
              #transactionId: transactionId,
              #total: total,
            }),
            returnValue: _i6.Future<_i3.RowList>.value(
              _FakeRowList_3(
                this,
                Invocation.method(#listRows, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #queries: queries,
                  #transactionId: transactionId,
                  #total: total,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.RowList>);

  @override
  _i6.Future<_i3.Row> createRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#createRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Row>);

  @override
  _i6.Future<_i3.Row> getRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    List<String>? queries,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #queries: queries,
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#getRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #queries: queries,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Row>);

  @override
  _i6.Future<_i3.Row> upsertRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#upsertRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Row>);

  @override
  _i6.Future<_i3.Row> updateRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#updateRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Row>);

  @override
  _i6.Future<dynamic> deleteRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.Row> decrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? min,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #min: min,
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#decrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #min: min,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Row>);

  @override
  _i6.Future<_i3.Row> incrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? max,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #max: max,
              #transactionId: transactionId,
            }),
            returnValue: _i6.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#incrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #max: max,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.Row>);
}

/// A class which mocks [Storage].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorage extends _i1.Mock implements _i5.Storage {
  MockStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.Future<_i3.FileList> listFiles({
    required String? bucketId,
    List<String>? queries,
    String? search,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listFiles, [], {
              #bucketId: bucketId,
              #queries: queries,
              #search: search,
              #total: total,
            }),
            returnValue: _i6.Future<_i3.FileList>.value(
              _FakeFileList_5(
                this,
                Invocation.method(#listFiles, [], {
                  #bucketId: bucketId,
                  #queries: queries,
                  #search: search,
                  #total: total,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.FileList>);

  @override
  _i6.Future<_i3.File> createFile({
    required String? bucketId,
    required String? fileId,
    required _i7.InputFile? file,
    List<String>? permissions,
    dynamic Function(_i8.UploadProgress)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFile, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #file: file,
              #permissions: permissions,
              #onProgress: onProgress,
            }),
            returnValue: _i6.Future<_i3.File>.value(
              _FakeFile_6(
                this,
                Invocation.method(#createFile, [], {
                  #bucketId: bucketId,
                  #fileId: fileId,
                  #file: file,
                  #permissions: permissions,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.File>);

  @override
  _i6.Future<_i3.File> getFile({
    required String? bucketId,
    required String? fileId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFile, [], {
              #bucketId: bucketId,
              #fileId: fileId,
            }),
            returnValue: _i6.Future<_i3.File>.value(
              _FakeFile_6(
                this,
                Invocation.method(#getFile, [], {
                  #bucketId: bucketId,
                  #fileId: fileId,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.File>);

  @override
  _i6.Future<_i3.File> updateFile({
    required String? bucketId,
    required String? fileId,
    String? name,
    List<String>? permissions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFile, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #name: name,
              #permissions: permissions,
            }),
            returnValue: _i6.Future<_i3.File>.value(
              _FakeFile_6(
                this,
                Invocation.method(#updateFile, [], {
                  #bucketId: bucketId,
                  #fileId: fileId,
                  #name: name,
                  #permissions: permissions,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.File>);

  @override
  _i6.Future<dynamic> deleteFile({
    required String? bucketId,
    required String? fileId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [], {
              #bucketId: bucketId,
              #fileId: fileId,
            }),
            returnValue: _i6.Future<dynamic>.value(),
          )
          as _i6.Future<dynamic>);

  @override
  _i6.Future<_i9.Uint8List> getFileDownload({
    required String? bucketId,
    required String? fileId,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFileDownload, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #token: token,
            }),
            returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i6.Future<_i9.Uint8List>);

  @override
  _i6.Future<_i9.Uint8List> getFilePreview({
    required String? bucketId,
    required String? fileId,
    int? width,
    int? height,
    _i10.ImageGravity? gravity,
    int? quality,
    int? borderWidth,
    String? borderColor,
    int? borderRadius,
    double? opacity,
    int? rotation,
    String? background,
    _i10.ImageFormat? output,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFilePreview, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #width: width,
              #height: height,
              #gravity: gravity,
              #quality: quality,
              #borderWidth: borderWidth,
              #borderColor: borderColor,
              #borderRadius: borderRadius,
              #opacity: opacity,
              #rotation: rotation,
              #background: background,
              #output: output,
              #token: token,
            }),
            returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i6.Future<_i9.Uint8List>);

  @override
  _i6.Future<_i9.Uint8List> getFileView({
    required String? bucketId,
    required String? fileId,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFileView, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #token: token,
            }),
            returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
          )
          as _i6.Future<_i9.Uint8List>);
}

/// A class which mocks [ThemeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeController extends _i1.Mock implements _i11.ThemeController {
  MockThemeController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Rx<String> get currentTheme =>
      (super.noSuchMethod(
            Invocation.getter(#currentTheme),
            returnValue: _FakeRx_7<String>(
              this,
              Invocation.getter(#currentTheme),
            ),
          )
          as _i4.Rx<String>);

  @override
  _i4.Rx<String> get currentThemePlaceHolder =>
      (super.noSuchMethod(
            Invocation.getter(#currentThemePlaceHolder),
            returnValue: _FakeRx_7<String>(
              this,
              Invocation.getter(#currentThemePlaceHolder),
            ),
          )
          as _i4.Rx<String>);

  @override
  String get getCurrentTheme =>
      (super.noSuchMethod(
            Invocation.getter(#getCurrentTheme),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#getCurrentTheme),
            ),
          )
          as String);

  @override
  String get userProfileImagePlaceholderUrl =>
      (super.noSuchMethod(
            Invocation.getter(#userProfileImagePlaceholderUrl),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#userProfileImagePlaceholderUrl),
            ),
          )
          as String);

  @override
  set currentTheme(_i4.Rx<String>? value) => super.noSuchMethod(
    Invocation.setter(#currentTheme, value),
    returnValueForMissingStub: null,
  );

  @override
  set currentThemePlaceHolder(_i4.Rx<String>? value) => super.noSuchMethod(
    Invocation.setter(#currentThemePlaceHolder, value),
    returnValueForMissingStub: null,
  );

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_8<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_8<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void updateTheme(String? theme) => super.noSuchMethod(
    Invocation.method(#updateTheme, [theme]),
    returnValueForMissingStub: null,
  );

  @override
  void updateUserProfileImagePlaceholderUrlOnTheme() => super.noSuchMethod(
    Invocation.method(#updateUserProfileImagePlaceholderUrlOnTheme, []),
    returnValueForMissingStub: null,
  );

  @override
  void setTheme(String? newTheme) => super.noSuchMethod(
    Invocation.method(#setTheme, [newTheme]),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListener(_i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i13.Disposer);

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i14.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListenerId(Object? key, _i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i13.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
