// Mocks generated by Mockito 5.4.6 from annotations
// in resonate/test/controllers/explore_story_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;

import 'package:appwrite/appwrite.dart' as _i4;
import 'package:appwrite/enums.dart' as _i9;
import 'package:appwrite/models.dart' as _i3;
import 'package:appwrite/src/client.dart' as _i2;
import 'package:appwrite/src/input_file.dart' as _i6;
import 'package:appwrite/src/upload_progress.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionList_1 extends _i1.SmartFake
    implements _i3.TransactionList {
  _FakeTransactionList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_2 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRowList_3 extends _i1.SmartFake implements _i3.RowList {
  _FakeRowList_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRow_4 extends _i1.SmartFake implements _i3.Row {
  _FakeRow_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileList_5 extends _i1.SmartFake implements _i3.FileList {
  _FakeFileList_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_6 extends _i1.SmartFake implements _i3.File {
  _FakeFile_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExecutionList_7 extends _i1.SmartFake implements _i3.ExecutionList {
  _FakeExecutionList_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExecution_8 extends _i1.SmartFake implements _i3.Execution {
  _FakeExecution_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TablesDB].
///
/// See the documentation for Mockito's code generation for more information.
class MockTablesDB extends _i1.Mock implements _i4.TablesDB {
  MockTablesDB() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<_i3.TransactionList> listTransactions({List<String>? queries}) =>
      (super.noSuchMethod(
            Invocation.method(#listTransactions, [], {#queries: queries}),
            returnValue: _i5.Future<_i3.TransactionList>.value(
              _FakeTransactionList_1(
                this,
                Invocation.method(#listTransactions, [], {#queries: queries}),
              ),
            ),
          )
          as _i5.Future<_i3.TransactionList>);

  @override
  _i5.Future<_i3.Transaction> createTransaction({int? ttl}) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {#ttl: ttl}),
            returnValue: _i5.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createTransaction, [], {#ttl: ttl}),
              ),
            ),
          )
          as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<_i3.Transaction> getTransaction({
    required String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#getTransaction, [], {
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<_i3.Transaction> updateTransaction({
    required String? transactionId,
    bool? commit,
    bool? rollback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [], {
              #transactionId: transactionId,
              #commit: commit,
              #rollback: rollback,
            }),
            returnValue: _i5.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#updateTransaction, [], {
                  #transactionId: transactionId,
                  #commit: commit,
                  #rollback: rollback,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<dynamic> deleteTransaction({required String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Transaction> createOperations({
    required String? transactionId,
    List<Map<dynamic, dynamic>>? operations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOperations, [], {
              #transactionId: transactionId,
              #operations: operations,
            }),
            returnValue: _i5.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createOperations, [], {
                  #transactionId: transactionId,
                  #operations: operations,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Transaction>);

  @override
  _i5.Future<_i3.RowList> listRows({
    required String? databaseId,
    required String? tableId,
    List<String>? queries,
    String? transactionId,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listRows, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #queries: queries,
              #transactionId: transactionId,
              #total: total,
            }),
            returnValue: _i5.Future<_i3.RowList>.value(
              _FakeRowList_3(
                this,
                Invocation.method(#listRows, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #queries: queries,
                  #transactionId: transactionId,
                  #total: total,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.RowList>);

  @override
  _i5.Future<_i3.Row> createRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#createRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<_i3.Row> getRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    List<String>? queries,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #queries: queries,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#getRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #queries: queries,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<_i3.Row> upsertRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#upsertRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<_i3.Row> updateRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#updateRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<dynamic> deleteRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.Row> decrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? min,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #min: min,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#decrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #min: min,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);

  @override
  _i5.Future<_i3.Row> incrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? max,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #max: max,
              #transactionId: transactionId,
            }),
            returnValue: _i5.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#incrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #max: max,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Row>);
}

/// A class which mocks [Storage].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorage extends _i1.Mock implements _i4.Storage {
  MockStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<_i3.FileList> listFiles({
    required String? bucketId,
    List<String>? queries,
    String? search,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listFiles, [], {
              #bucketId: bucketId,
              #queries: queries,
              #search: search,
              #total: total,
            }),
            returnValue: _i5.Future<_i3.FileList>.value(
              _FakeFileList_5(
                this,
                Invocation.method(#listFiles, [], {
                  #bucketId: bucketId,
                  #queries: queries,
                  #search: search,
                  #total: total,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.FileList>);

  @override
  _i5.Future<_i3.File> createFile({
    required String? bucketId,
    required String? fileId,
    required _i6.InputFile? file,
    List<String>? permissions,
    dynamic Function(_i7.UploadProgress)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFile, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #file: file,
              #permissions: permissions,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<_i3.File>.value(
              _FakeFile_6(
                this,
                Invocation.method(#createFile, [], {
                  #bucketId: bucketId,
                  #fileId: fileId,
                  #file: file,
                  #permissions: permissions,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.File>);

  @override
  _i5.Future<_i3.File> getFile({
    required String? bucketId,
    required String? fileId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFile, [], {
              #bucketId: bucketId,
              #fileId: fileId,
            }),
            returnValue: _i5.Future<_i3.File>.value(
              _FakeFile_6(
                this,
                Invocation.method(#getFile, [], {
                  #bucketId: bucketId,
                  #fileId: fileId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.File>);

  @override
  _i5.Future<_i3.File> updateFile({
    required String? bucketId,
    required String? fileId,
    String? name,
    List<String>? permissions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFile, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #name: name,
              #permissions: permissions,
            }),
            returnValue: _i5.Future<_i3.File>.value(
              _FakeFile_6(
                this,
                Invocation.method(#updateFile, [], {
                  #bucketId: bucketId,
                  #fileId: fileId,
                  #name: name,
                  #permissions: permissions,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.File>);

  @override
  _i5.Future<dynamic> deleteFile({
    required String? bucketId,
    required String? fileId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFile, [], {
              #bucketId: bucketId,
              #fileId: fileId,
            }),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<_i8.Uint8List> getFileDownload({
    required String? bucketId,
    required String? fileId,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFileDownload, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #token: token,
            }),
            returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
          )
          as _i5.Future<_i8.Uint8List>);

  @override
  _i5.Future<_i8.Uint8List> getFilePreview({
    required String? bucketId,
    required String? fileId,
    int? width,
    int? height,
    _i9.ImageGravity? gravity,
    int? quality,
    int? borderWidth,
    String? borderColor,
    int? borderRadius,
    double? opacity,
    int? rotation,
    String? background,
    _i9.ImageFormat? output,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFilePreview, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #width: width,
              #height: height,
              #gravity: gravity,
              #quality: quality,
              #borderWidth: borderWidth,
              #borderColor: borderColor,
              #borderRadius: borderRadius,
              #opacity: opacity,
              #rotation: rotation,
              #background: background,
              #output: output,
              #token: token,
            }),
            returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
          )
          as _i5.Future<_i8.Uint8List>);

  @override
  _i5.Future<_i8.Uint8List> getFileView({
    required String? bucketId,
    required String? fileId,
    String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFileView, [], {
              #bucketId: bucketId,
              #fileId: fileId,
              #token: token,
            }),
            returnValue: _i5.Future<_i8.Uint8List>.value(_i8.Uint8List(0)),
          )
          as _i5.Future<_i8.Uint8List>);
}

/// A class which mocks [Functions].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctions extends _i1.Mock implements _i4.Functions {
  MockFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<_i3.ExecutionList> listExecutions({
    required String? functionId,
    List<String>? queries,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listExecutions, [], {
              #functionId: functionId,
              #queries: queries,
              #total: total,
            }),
            returnValue: _i5.Future<_i3.ExecutionList>.value(
              _FakeExecutionList_7(
                this,
                Invocation.method(#listExecutions, [], {
                  #functionId: functionId,
                  #queries: queries,
                  #total: total,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ExecutionList>);

  @override
  _i5.Future<_i3.Execution> createExecution({
    required String? functionId,
    String? body,
    bool? xasync,
    String? path,
    _i9.ExecutionMethod? method,
    Map<dynamic, dynamic>? headers,
    String? scheduledAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createExecution, [], {
              #functionId: functionId,
              #body: body,
              #xasync: xasync,
              #path: path,
              #method: method,
              #headers: headers,
              #scheduledAt: scheduledAt,
            }),
            returnValue: _i5.Future<_i3.Execution>.value(
              _FakeExecution_8(
                this,
                Invocation.method(#createExecution, [], {
                  #functionId: functionId,
                  #body: body,
                  #xasync: xasync,
                  #path: path,
                  #method: method,
                  #headers: headers,
                  #scheduledAt: scheduledAt,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Execution>);

  @override
  _i5.Future<_i3.Execution> getExecution({
    required String? functionId,
    required String? executionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExecution, [], {
              #functionId: functionId,
              #executionId: executionId,
            }),
            returnValue: _i5.Future<_i3.Execution>.value(
              _FakeExecution_8(
                this,
                Invocation.method(#getExecution, [], {
                  #functionId: functionId,
                  #executionId: executionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Execution>);
}
