// Mocks generated by Mockito 5.4.6 from annotations
// in resonate/test/controllers/friends_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i16;

import 'package:appwrite/appwrite.dart' as _i6;
import 'package:appwrite/enums.dart' as _i11;
import 'package:appwrite/models.dart' as _i3;
import 'package:appwrite/src/client.dart' as _i2;
import 'package:appwrite/src/enums.dart' as _i19;
import 'package:appwrite/src/upload_progress.dart' as _i18;
import 'package:firebase_core/firebase_core.dart' as _i4;
import 'package:firebase_messaging/firebase_messaging.dart' as _i8;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i5;
import 'package:flutter/material.dart' as _i14;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i9;
import 'package:get/get.dart' as _i7;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;
import 'package:resonate/controllers/auth_state_controller.dart' as _i12;
import 'package:resonate/models/follower_user_model.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionList_1 extends _i1.SmartFake
    implements _i3.TransactionList {
  _FakeTransactionList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_2 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRowList_3 extends _i1.SmartFake implements _i3.RowList {
  _FakeRowList_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRow_4 extends _i1.SmartFake implements _i3.Row {
  _FakeRow_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExecutionList_5 extends _i1.SmartFake implements _i3.ExecutionList {
  _FakeExecutionList_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExecution_6 extends _i1.SmartFake implements _i3.Execution {
  _FakeExecution_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_7 extends _i1.SmartFake implements _i4.FirebaseApp {
  _FakeFirebaseApp_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettings_8 extends _i1.SmartFake
    implements _i5.NotificationSettings {
  _FakeNotificationSettings_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTablesDB_9 extends _i1.SmartFake implements _i6.TablesDB {
  _FakeTablesDB_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_10 extends _i1.SmartFake implements _i7.RxBool {
  _FakeRxBool_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseMessaging_11 extends _i1.SmartFake
    implements _i8.FirebaseMessaging {
  _FakeFirebaseMessaging_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccount_12 extends _i1.SmartFake implements _i6.Account {
  _FakeAccount_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_13 extends _i1.SmartFake implements _i3.User {
  _FakeUser_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterLocalNotificationsPlugin_14 extends _i1.SmartFake
    implements _i9.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_15<T> extends _i1.SmartFake
    implements _i7.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdentityList_16 extends _i1.SmartFake implements _i3.IdentityList {
  _FakeIdentityList_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJwt_17 extends _i1.SmartFake implements _i3.Jwt {
  _FakeJwt_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogList_18 extends _i1.SmartFake implements _i3.LogList {
  _FakeLogList_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaType_19 extends _i1.SmartFake implements _i3.MfaType {
  _FakeMfaType_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaChallenge_20 extends _i1.SmartFake implements _i3.MfaChallenge {
  _FakeMfaChallenge_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSession_21 extends _i1.SmartFake implements _i3.Session {
  _FakeSession_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaFactors_22 extends _i1.SmartFake implements _i3.MfaFactors {
  _FakeMfaFactors_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMfaRecoveryCodes_23 extends _i1.SmartFake
    implements _i3.MfaRecoveryCodes {
  _FakeMfaRecoveryCodes_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePreferences_24 extends _i1.SmartFake implements _i3.Preferences {
  _FakePreferences_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeToken_25 extends _i1.SmartFake implements _i3.Token {
  _FakeToken_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionList_26 extends _i1.SmartFake implements _i3.SessionList {
  _FakeSessionList_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTarget_27 extends _i1.SmartFake implements _i3.Target {
  _FakeTarget_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_28<T> extends _i1.SmartFake implements _i6.Response<T> {
  _FakeResponse_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeSubscription_29 extends _i1.SmartFake
    implements _i6.RealtimeSubscription {
  _FakeRealtimeSubscription_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TablesDB].
///
/// See the documentation for Mockito's code generation for more information.
class MockTablesDB extends _i1.Mock implements _i6.TablesDB {
  MockTablesDB() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i10.Future<_i3.TransactionList> listTransactions({List<String>? queries}) =>
      (super.noSuchMethod(
            Invocation.method(#listTransactions, [], {#queries: queries}),
            returnValue: _i10.Future<_i3.TransactionList>.value(
              _FakeTransactionList_1(
                this,
                Invocation.method(#listTransactions, [], {#queries: queries}),
              ),
            ),
          )
          as _i10.Future<_i3.TransactionList>);

  @override
  _i10.Future<_i3.Transaction> createTransaction({int? ttl}) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {#ttl: ttl}),
            returnValue: _i10.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createTransaction, [], {#ttl: ttl}),
              ),
            ),
          )
          as _i10.Future<_i3.Transaction>);

  @override
  _i10.Future<_i3.Transaction> getTransaction({
    required String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#getTransaction, [], {
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Transaction>);

  @override
  _i10.Future<_i3.Transaction> updateTransaction({
    required String? transactionId,
    bool? commit,
    bool? rollback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [], {
              #transactionId: transactionId,
              #commit: commit,
              #rollback: rollback,
            }),
            returnValue: _i10.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#updateTransaction, [], {
                  #transactionId: transactionId,
                  #commit: commit,
                  #rollback: rollback,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Transaction>);

  @override
  _i10.Future<dynamic> deleteTransaction({required String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.Transaction> createOperations({
    required String? transactionId,
    List<Map<dynamic, dynamic>>? operations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOperations, [], {
              #transactionId: transactionId,
              #operations: operations,
            }),
            returnValue: _i10.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createOperations, [], {
                  #transactionId: transactionId,
                  #operations: operations,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Transaction>);

  @override
  _i10.Future<_i3.RowList> listRows({
    required String? databaseId,
    required String? tableId,
    List<String>? queries,
    String? transactionId,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listRows, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #queries: queries,
              #transactionId: transactionId,
              #total: total,
            }),
            returnValue: _i10.Future<_i3.RowList>.value(
              _FakeRowList_3(
                this,
                Invocation.method(#listRows, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #queries: queries,
                  #transactionId: transactionId,
                  #total: total,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.RowList>);

  @override
  _i10.Future<_i3.Row> createRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#createRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Row>);

  @override
  _i10.Future<_i3.Row> getRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    List<String>? queries,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #queries: queries,
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#getRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #queries: queries,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Row>);

  @override
  _i10.Future<_i3.Row> upsertRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#upsertRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Row>);

  @override
  _i10.Future<_i3.Row> updateRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#updateRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Row>);

  @override
  _i10.Future<dynamic> deleteRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.Row> decrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? min,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #min: min,
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#decrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #min: min,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Row>);

  @override
  _i10.Future<_i3.Row> incrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? max,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #max: max,
              #transactionId: transactionId,
            }),
            returnValue: _i10.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#incrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #max: max,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Row>);
}

/// A class which mocks [Functions].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctions extends _i1.Mock implements _i6.Functions {
  MockFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i10.Future<_i3.ExecutionList> listExecutions({
    required String? functionId,
    List<String>? queries,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listExecutions, [], {
              #functionId: functionId,
              #queries: queries,
              #total: total,
            }),
            returnValue: _i10.Future<_i3.ExecutionList>.value(
              _FakeExecutionList_5(
                this,
                Invocation.method(#listExecutions, [], {
                  #functionId: functionId,
                  #queries: queries,
                  #total: total,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.ExecutionList>);

  @override
  _i10.Future<_i3.Execution> createExecution({
    required String? functionId,
    String? body,
    bool? xasync,
    String? path,
    _i11.ExecutionMethod? method,
    Map<dynamic, dynamic>? headers,
    String? scheduledAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createExecution, [], {
              #functionId: functionId,
              #body: body,
              #xasync: xasync,
              #path: path,
              #method: method,
              #headers: headers,
              #scheduledAt: scheduledAt,
            }),
            returnValue: _i10.Future<_i3.Execution>.value(
              _FakeExecution_6(
                this,
                Invocation.method(#createExecution, [], {
                  #functionId: functionId,
                  #body: body,
                  #xasync: xasync,
                  #path: path,
                  #method: method,
                  #headers: headers,
                  #scheduledAt: scheduledAt,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Execution>);

  @override
  _i10.Future<_i3.Execution> getExecution({
    required String? functionId,
    required String? executionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExecution, [], {
              #functionId: functionId,
              #executionId: executionId,
            }),
            returnValue: _i10.Future<_i3.Execution>.value(
              _FakeExecution_6(
                this,
                Invocation.method(#getExecution, [], {
                  #functionId: functionId,
                  #executionId: executionId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Execution>);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i8.FirebaseMessaging {
  MockFirebaseMessaging() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_7(this, Invocation.getter(#app)),
          )
          as _i4.FirebaseApp);

  @override
  bool get isAutoInitEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoInitEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i10.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i10.Stream<String>.empty(),
          )
          as _i10.Stream<String>);

  @override
  set app(_i4.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i10.Future<_i5.RemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i10.Future<_i5.RemoteMessage?>.value(),
          )
          as _i10.Future<_i5.RemoteMessage?>);

  @override
  _i10.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String?> getAPNSToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAPNSToken, []),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<String?> getToken({String? vapidKey}) =>
      (super.noSuchMethod(
            Invocation.method(#getToken, [], {#vapidKey: vapidKey}),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i5.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationSettings, []),
            returnValue: _i10.Future<_i5.NotificationSettings>.value(
              _FakeNotificationSettings_8(
                this,
                Invocation.method(#getNotificationSettings, []),
              ),
            ),
          )
          as _i10.Future<_i5.NotificationSettings>);

  @override
  _i10.Future<_i5.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
    bool? providesAppNotificationSettings = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, [], {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
              #providesAppNotificationSettings: providesAppNotificationSettings,
            }),
            returnValue: _i10.Future<_i5.NotificationSettings>.value(
              _FakeNotificationSettings_8(
                this,
                Invocation.method(#requestPermission, [], {
                  #alert: alert,
                  #announcement: announcement,
                  #badge: badge,
                  #carPlay: carPlay,
                  #criticalAlert: criticalAlert,
                  #provisional: provisional,
                  #sound: sound,
                  #providesAppNotificationSettings:
                      providesAppNotificationSettings,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.NotificationSettings>);

  @override
  _i10.Future<void> setAutoInitEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoInitEnabled, [enabled]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setDeliveryMetricsExportToBigQuery, [enabled]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setForegroundNotificationPresentationOptions,
              [],
              {#alert: alert, #badge: badge, #sound: sound},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [AuthStateController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStateController extends _i1.Mock
    implements _i12.AuthStateController {
  MockAuthStateController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.TablesDB get tables =>
      (super.noSuchMethod(
            Invocation.getter(#tables),
            returnValue: _FakeTablesDB_9(this, Invocation.getter(#tables)),
          )
          as _i6.TablesDB);

  @override
  _i7.RxBool get isInitializing =>
      (super.noSuchMethod(
            Invocation.getter(#isInitializing),
            returnValue: _FakeRxBool_10(
              this,
              Invocation.getter(#isInitializing),
            ),
          )
          as _i7.RxBool);

  @override
  _i8.FirebaseMessaging get messaging =>
      (super.noSuchMethod(
            Invocation.getter(#messaging),
            returnValue: _FakeFirebaseMessaging_11(
              this,
              Invocation.getter(#messaging),
            ),
          )
          as _i8.FirebaseMessaging);

  @override
  _i6.Account get account =>
      (super.noSuchMethod(
            Invocation.getter(#account),
            returnValue: _FakeAccount_12(this, Invocation.getter(#account)),
          )
          as _i6.Account);

  @override
  double get ratingTotal =>
      (super.noSuchMethod(Invocation.getter(#ratingTotal), returnValue: 0.0)
          as double);

  @override
  int get ratingCount =>
      (super.noSuchMethod(Invocation.getter(#ratingCount), returnValue: 0)
          as int);

  @override
  _i3.User get appwriteUser =>
      (super.noSuchMethod(
            Invocation.getter(#appwriteUser),
            returnValue: _FakeUser_13(this, Invocation.getter(#appwriteUser)),
          )
          as _i3.User);

  @override
  List<_i13.FollowerUserModel> get followerDocuments =>
      (super.noSuchMethod(
            Invocation.getter(#followerDocuments),
            returnValue: <_i13.FollowerUserModel>[],
          )
          as List<_i13.FollowerUserModel>);

  @override
  int get reportsCount =>
      (super.noSuchMethod(Invocation.getter(#reportsCount), returnValue: 0)
          as int);

  @override
  _i9.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(
            Invocation.getter(#flutterLocalNotificationsPlugin),
            returnValue: _FakeFlutterLocalNotificationsPlugin_14(
              this,
              Invocation.getter(#flutterLocalNotificationsPlugin),
            ),
          )
          as _i9.FlutterLocalNotificationsPlugin);

  @override
  _i10.Future<bool> get getLoginState =>
      (super.noSuchMethod(
            Invocation.getter(#getLoginState),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  set client(_i2.Client? value) => super.noSuchMethod(
    Invocation.setter(#client, value),
    returnValueForMissingStub: null,
  );

  @override
  set isInitializing(_i7.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isInitializing, value),
    returnValueForMissingStub: null,
  );

  @override
  set messaging(_i8.FirebaseMessaging? value) => super.noSuchMethod(
    Invocation.setter(#messaging, value),
    returnValueForMissingStub: null,
  );

  @override
  set account(_i6.Account? value) => super.noSuchMethod(
    Invocation.setter(#account, value),
    returnValueForMissingStub: null,
  );

  @override
  set uid(String? value) => super.noSuchMethod(
    Invocation.setter(#uid, value),
    returnValueForMissingStub: null,
  );

  @override
  set profileImageID(String? value) => super.noSuchMethod(
    Invocation.setter(#profileImageID, value),
    returnValueForMissingStub: null,
  );

  @override
  set displayName(String? value) => super.noSuchMethod(
    Invocation.setter(#displayName, value),
    returnValueForMissingStub: null,
  );

  @override
  set email(String? value) => super.noSuchMethod(
    Invocation.setter(#email, value),
    returnValueForMissingStub: null,
  );

  @override
  set profileImageUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#profileImageUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set userName(String? value) => super.noSuchMethod(
    Invocation.setter(#userName, value),
    returnValueForMissingStub: null,
  );

  @override
  set isUserProfileComplete(bool? value) => super.noSuchMethod(
    Invocation.setter(#isUserProfileComplete, value),
    returnValueForMissingStub: null,
  );

  @override
  set isEmailVerified(bool? value) => super.noSuchMethod(
    Invocation.setter(#isEmailVerified, value),
    returnValueForMissingStub: null,
  );

  @override
  set ratingTotal(double? value) => super.noSuchMethod(
    Invocation.setter(#ratingTotal, value),
    returnValueForMissingStub: null,
  );

  @override
  set ratingCount(int? value) => super.noSuchMethod(
    Invocation.setter(#ratingCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set appwriteUser(_i3.User? value) => super.noSuchMethod(
    Invocation.setter(#appwriteUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set followerDocuments(List<_i13.FollowerUserModel>? value) =>
      super.noSuchMethod(
        Invocation.setter(#followerDocuments, value),
        returnValueForMissingStub: null,
      );

  @override
  set reportsCount(int? value) => super.noSuchMethod(
    Invocation.setter(#reportsCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set flutterLocalNotificationsPlugin(
    _i9.FlutterLocalNotificationsPlugin? value,
  ) => super.noSuchMethod(
    Invocation.setter(#flutterLocalNotificationsPlugin, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_15<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i7.InternalFinalCallback<void>);

  @override
  _i7.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_15<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i7.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  _i10.Future<void> initializeLocalNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#initializeLocalNotifications, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onDidReceiveNotificationResponse(
    _i9.NotificationResponse? notificationResponse,
  ) => super.noSuchMethod(
    Invocation.method(#onDidReceiveNotificationResponse, [
      notificationResponse,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> setUserProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#setUserProfileData, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> addRegistrationTokentoSubscribedandCreatedUpcomingRooms() =>
      (super.noSuchMethod(
            Invocation.method(
              #addRegistrationTokentoSubscribedandCreatedUpcomingRooms,
              [],
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> removeRegistrationTokenFromSubscribedUpcomingRooms() =>
      (super.noSuchMethod(
            Invocation.method(
              #removeRegistrationTokenFromSubscribedUpcomingRooms,
              [],
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> signup(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [email, password]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loginWithGithub() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGithub, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> logout(_i14.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [context]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Disposer addListener(_i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i15.Disposer);

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i16.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Disposer addListenerId(Object? key, _i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i15.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [Account].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccount extends _i1.Mock implements _i6.Account {
  MockAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i10.Future<_i3.User> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(this, Invocation.method(#get, [])),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.User> create({
    required String? userId,
    required String? email,
    required String? password,
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #userId: userId,
              #email: email,
              #password: password,
              #name: name,
            }),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#create, [], {
                  #userId: userId,
                  #email: email,
                  #password: password,
                  #name: name,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.User> updateEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updateEmail, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.IdentityList> listIdentities({
    List<String>? queries,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listIdentities, [], {
              #queries: queries,
              #total: total,
            }),
            returnValue: _i10.Future<_i3.IdentityList>.value(
              _FakeIdentityList_16(
                this,
                Invocation.method(#listIdentities, [], {
                  #queries: queries,
                  #total: total,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.IdentityList>);

  @override
  _i10.Future<dynamic> deleteIdentity({required String? identityId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIdentity, [], {#identityId: identityId}),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.Jwt> createJWT() =>
      (super.noSuchMethod(
            Invocation.method(#createJWT, []),
            returnValue: _i10.Future<_i3.Jwt>.value(
              _FakeJwt_17(this, Invocation.method(#createJWT, [])),
            ),
          )
          as _i10.Future<_i3.Jwt>);

  @override
  _i10.Future<_i3.LogList> listLogs({List<String>? queries, bool? total}) =>
      (super.noSuchMethod(
            Invocation.method(#listLogs, [], {
              #queries: queries,
              #total: total,
            }),
            returnValue: _i10.Future<_i3.LogList>.value(
              _FakeLogList_18(
                this,
                Invocation.method(#listLogs, [], {
                  #queries: queries,
                  #total: total,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.LogList>);

  @override
  _i10.Future<_i3.User> updateMFA({required bool? mfa}) =>
      (super.noSuchMethod(
            Invocation.method(#updateMFA, [], {#mfa: mfa}),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updateMFA, [], {#mfa: mfa}),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.MfaType> createMfaAuthenticator({
    required _i11.AuthenticatorType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMfaAuthenticator, [], {#type: type}),
            returnValue: _i10.Future<_i3.MfaType>.value(
              _FakeMfaType_19(
                this,
                Invocation.method(#createMfaAuthenticator, [], {#type: type}),
              ),
            ),
          )
          as _i10.Future<_i3.MfaType>);

  @override
  _i10.Future<_i3.MfaType> createMFAAuthenticator({
    required _i11.AuthenticatorType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMFAAuthenticator, [], {#type: type}),
            returnValue: _i10.Future<_i3.MfaType>.value(
              _FakeMfaType_19(
                this,
                Invocation.method(#createMFAAuthenticator, [], {#type: type}),
              ),
            ),
          )
          as _i10.Future<_i3.MfaType>);

  @override
  _i10.Future<_i3.User> updateMfaAuthenticator({
    required _i11.AuthenticatorType? type,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMfaAuthenticator, [], {
              #type: type,
              #otp: otp,
            }),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updateMfaAuthenticator, [], {
                  #type: type,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.User> updateMFAAuthenticator({
    required _i11.AuthenticatorType? type,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMFAAuthenticator, [], {
              #type: type,
              #otp: otp,
            }),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updateMFAAuthenticator, [], {
                  #type: type,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<dynamic> deleteMfaAuthenticator({
    required _i11.AuthenticatorType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMfaAuthenticator, [], {#type: type}),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> deleteMFAAuthenticator({
    required _i11.AuthenticatorType? type,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMFAAuthenticator, [], {#type: type}),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.MfaChallenge> createMfaChallenge({
    required _i11.AuthenticationFactor? factor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMfaChallenge, [], {#factor: factor}),
            returnValue: _i10.Future<_i3.MfaChallenge>.value(
              _FakeMfaChallenge_20(
                this,
                Invocation.method(#createMfaChallenge, [], {#factor: factor}),
              ),
            ),
          )
          as _i10.Future<_i3.MfaChallenge>);

  @override
  _i10.Future<_i3.MfaChallenge> createMFAChallenge({
    required _i11.AuthenticationFactor? factor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMFAChallenge, [], {#factor: factor}),
            returnValue: _i10.Future<_i3.MfaChallenge>.value(
              _FakeMfaChallenge_20(
                this,
                Invocation.method(#createMFAChallenge, [], {#factor: factor}),
              ),
            ),
          )
          as _i10.Future<_i3.MfaChallenge>);

  @override
  _i10.Future<_i3.Session> updateMfaChallenge({
    required String? challengeId,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMfaChallenge, [], {
              #challengeId: challengeId,
              #otp: otp,
            }),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#updateMfaChallenge, [], {
                  #challengeId: challengeId,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<_i3.Session> updateMFAChallenge({
    required String? challengeId,
    required String? otp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMFAChallenge, [], {
              #challengeId: challengeId,
              #otp: otp,
            }),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#updateMFAChallenge, [], {
                  #challengeId: challengeId,
                  #otp: otp,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<_i3.MfaFactors> listMfaFactors() =>
      (super.noSuchMethod(
            Invocation.method(#listMfaFactors, []),
            returnValue: _i10.Future<_i3.MfaFactors>.value(
              _FakeMfaFactors_22(this, Invocation.method(#listMfaFactors, [])),
            ),
          )
          as _i10.Future<_i3.MfaFactors>);

  @override
  _i10.Future<_i3.MfaFactors> listMFAFactors() =>
      (super.noSuchMethod(
            Invocation.method(#listMFAFactors, []),
            returnValue: _i10.Future<_i3.MfaFactors>.value(
              _FakeMfaFactors_22(this, Invocation.method(#listMFAFactors, [])),
            ),
          )
          as _i10.Future<_i3.MfaFactors>);

  @override
  _i10.Future<_i3.MfaRecoveryCodes> getMfaRecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#getMfaRecoveryCodes, []),
            returnValue: _i10.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_23(
                this,
                Invocation.method(#getMfaRecoveryCodes, []),
              ),
            ),
          )
          as _i10.Future<_i3.MfaRecoveryCodes>);

  @override
  _i10.Future<_i3.MfaRecoveryCodes> getMFARecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#getMFARecoveryCodes, []),
            returnValue: _i10.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_23(
                this,
                Invocation.method(#getMFARecoveryCodes, []),
              ),
            ),
          )
          as _i10.Future<_i3.MfaRecoveryCodes>);

  @override
  _i10.Future<_i3.MfaRecoveryCodes> createMfaRecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#createMfaRecoveryCodes, []),
            returnValue: _i10.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_23(
                this,
                Invocation.method(#createMfaRecoveryCodes, []),
              ),
            ),
          )
          as _i10.Future<_i3.MfaRecoveryCodes>);

  @override
  _i10.Future<_i3.MfaRecoveryCodes> createMFARecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#createMFARecoveryCodes, []),
            returnValue: _i10.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_23(
                this,
                Invocation.method(#createMFARecoveryCodes, []),
              ),
            ),
          )
          as _i10.Future<_i3.MfaRecoveryCodes>);

  @override
  _i10.Future<_i3.MfaRecoveryCodes> updateMfaRecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#updateMfaRecoveryCodes, []),
            returnValue: _i10.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_23(
                this,
                Invocation.method(#updateMfaRecoveryCodes, []),
              ),
            ),
          )
          as _i10.Future<_i3.MfaRecoveryCodes>);

  @override
  _i10.Future<_i3.MfaRecoveryCodes> updateMFARecoveryCodes() =>
      (super.noSuchMethod(
            Invocation.method(#updateMFARecoveryCodes, []),
            returnValue: _i10.Future<_i3.MfaRecoveryCodes>.value(
              _FakeMfaRecoveryCodes_23(
                this,
                Invocation.method(#updateMFARecoveryCodes, []),
              ),
            ),
          )
          as _i10.Future<_i3.MfaRecoveryCodes>);

  @override
  _i10.Future<_i3.User> updateName({required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [], {#name: name}),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updateName, [], {#name: name}),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.User> updatePassword({
    required String? password,
    String? oldPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #password: password,
              #oldPassword: oldPassword,
            }),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updatePassword, [], {
                  #password: password,
                  #oldPassword: oldPassword,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.User> updatePhone({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhone, [], {
              #phone: phone,
              #password: password,
            }),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updatePhone, [], {
                  #phone: phone,
                  #password: password,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.Preferences> getPrefs() =>
      (super.noSuchMethod(
            Invocation.method(#getPrefs, []),
            returnValue: _i10.Future<_i3.Preferences>.value(
              _FakePreferences_24(this, Invocation.method(#getPrefs, [])),
            ),
          )
          as _i10.Future<_i3.Preferences>);

  @override
  _i10.Future<_i3.User> updatePrefs({required Map<dynamic, dynamic>? prefs}) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrefs, [], {#prefs: prefs}),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(
                this,
                Invocation.method(#updatePrefs, [], {#prefs: prefs}),
              ),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.Token> createRecovery({
    required String? email,
    required String? url,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRecovery, [], {#email: email, #url: url}),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#createRecovery, [], {
                  #email: email,
                  #url: url,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.Token> updateRecovery({
    required String? userId,
    required String? secret,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecovery, [], {
              #userId: userId,
              #secret: secret,
              #password: password,
            }),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#updateRecovery, [], {
                  #userId: userId,
                  #secret: secret,
                  #password: password,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.SessionList> listSessions() =>
      (super.noSuchMethod(
            Invocation.method(#listSessions, []),
            returnValue: _i10.Future<_i3.SessionList>.value(
              _FakeSessionList_26(this, Invocation.method(#listSessions, [])),
            ),
          )
          as _i10.Future<_i3.SessionList>);

  @override
  _i10.Future<dynamic> deleteSessions() =>
      (super.noSuchMethod(
            Invocation.method(#deleteSessions, []),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.Session> createAnonymousSession() =>
      (super.noSuchMethod(
            Invocation.method(#createAnonymousSession, []),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#createAnonymousSession, []),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<_i3.Session> createEmailPasswordSession({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmailPasswordSession, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#createEmailPasswordSession, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<_i3.Session> updateMagicURLSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateMagicURLSession, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#updateMagicURLSession, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<dynamic> createOAuth2Session({
    required _i11.OAuthProvider? provider,
    String? success,
    String? failure,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOAuth2Session, [], {
              #provider: provider,
              #success: success,
              #failure: failure,
              #scopes: scopes,
            }),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.Session> updatePhoneSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneSession, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#updatePhoneSession, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<_i3.Session> createSession({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSession, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#createSession, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<_i3.Session> getSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#getSession, [], {#sessionId: sessionId}),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#getSession, [], {#sessionId: sessionId}),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<_i3.Session> updateSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#updateSession, [], {#sessionId: sessionId}),
            returnValue: _i10.Future<_i3.Session>.value(
              _FakeSession_21(
                this,
                Invocation.method(#updateSession, [], {#sessionId: sessionId}),
              ),
            ),
          )
          as _i10.Future<_i3.Session>);

  @override
  _i10.Future<dynamic> deleteSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [], {#sessionId: sessionId}),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.User> updateStatus() =>
      (super.noSuchMethod(
            Invocation.method(#updateStatus, []),
            returnValue: _i10.Future<_i3.User>.value(
              _FakeUser_13(this, Invocation.method(#updateStatus, [])),
            ),
          )
          as _i10.Future<_i3.User>);

  @override
  _i10.Future<_i3.Target> createPushTarget({
    required String? targetId,
    required String? identifier,
    String? providerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPushTarget, [], {
              #targetId: targetId,
              #identifier: identifier,
              #providerId: providerId,
            }),
            returnValue: _i10.Future<_i3.Target>.value(
              _FakeTarget_27(
                this,
                Invocation.method(#createPushTarget, [], {
                  #targetId: targetId,
                  #identifier: identifier,
                  #providerId: providerId,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Target>);

  @override
  _i10.Future<_i3.Target> updatePushTarget({
    required String? targetId,
    required String? identifier,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePushTarget, [], {
              #targetId: targetId,
              #identifier: identifier,
            }),
            returnValue: _i10.Future<_i3.Target>.value(
              _FakeTarget_27(
                this,
                Invocation.method(#updatePushTarget, [], {
                  #targetId: targetId,
                  #identifier: identifier,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Target>);

  @override
  _i10.Future<dynamic> deletePushTarget({required String? targetId}) =>
      (super.noSuchMethod(
            Invocation.method(#deletePushTarget, [], {#targetId: targetId}),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.Token> createEmailToken({
    required String? userId,
    required String? email,
    bool? phrase,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createEmailToken, [], {
              #userId: userId,
              #email: email,
              #phrase: phrase,
            }),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#createEmailToken, [], {
                  #userId: userId,
                  #email: email,
                  #phrase: phrase,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.Token> createMagicURLToken({
    required String? userId,
    required String? email,
    String? url,
    bool? phrase,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMagicURLToken, [], {
              #userId: userId,
              #email: email,
              #url: url,
              #phrase: phrase,
            }),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#createMagicURLToken, [], {
                  #userId: userId,
                  #email: email,
                  #url: url,
                  #phrase: phrase,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<dynamic> createOAuth2Token({
    required _i11.OAuthProvider? provider,
    String? success,
    String? failure,
    List<String>? scopes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOAuth2Token, [], {
              #provider: provider,
              #success: success,
              #failure: failure,
              #scopes: scopes,
            }),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i3.Token> createPhoneToken({
    required String? userId,
    required String? phone,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPhoneToken, [], {
              #userId: userId,
              #phone: phone,
            }),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#createPhoneToken, [], {
                  #userId: userId,
                  #phone: phone,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.Token> createEmailVerification({required String? url}) =>
      (super.noSuchMethod(
            Invocation.method(#createEmailVerification, [], {#url: url}),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#createEmailVerification, [], {#url: url}),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.Token> createVerification({required String? url}) =>
      (super.noSuchMethod(
            Invocation.method(#createVerification, [], {#url: url}),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#createVerification, [], {#url: url}),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.Token> updateEmailVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmailVerification, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#updateEmailVerification, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.Token> updateVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateVerification, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#updateVerification, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.Token> createPhoneVerification() =>
      (super.noSuchMethod(
            Invocation.method(#createPhoneVerification, []),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#createPhoneVerification, []),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);

  @override
  _i10.Future<_i3.Token> updatePhoneVerification({
    required String? userId,
    required String? secret,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneVerification, [], {
              #userId: userId,
              #secret: secret,
            }),
            returnValue: _i10.Future<_i3.Token>.value(
              _FakeToken_25(
                this,
                Invocation.method(#updatePhoneVerification, [], {
                  #userId: userId,
                  #secret: secret,
                }),
              ),
            ),
          )
          as _i10.Future<_i3.Token>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i2.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  String get endPoint =>
      (super.noSuchMethod(
            Invocation.getter(#endPoint),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#endPoint),
            ),
          )
          as String);

  @override
  set config(Map<String, String>? value) => super.noSuchMethod(
    Invocation.setter(#config, value),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<dynamic> webAuth(Uri? url, {String? callbackUrlScheme}) =>
      (super.noSuchMethod(
            Invocation.method(
              #webAuth,
              [url],
              {#callbackUrlScheme: callbackUrlScheme},
            ),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<_i6.Response<dynamic>> chunkedUpload({
    required String? path,
    required Map<String, dynamic>? params,
    required String? paramName,
    required String? idParamName,
    required Map<String, String>? headers,
    dynamic Function(_i18.UploadProgress)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#chunkedUpload, [], {
              #path: path,
              #params: params,
              #paramName: paramName,
              #idParamName: idParamName,
              #headers: headers,
              #onProgress: onProgress,
            }),
            returnValue: _i10.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_28<dynamic>(
                this,
                Invocation.method(#chunkedUpload, [], {
                  #path: path,
                  #params: params,
                  #paramName: paramName,
                  #idParamName: idParamName,
                  #headers: headers,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i10.Future<_i6.Response<dynamic>>);

  @override
  _i2.Client setSelfSigned({bool? status = true}) =>
      (super.noSuchMethod(
            Invocation.method(#setSelfSigned, [], {#status: status}),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#setSelfSigned, [], {#status: status}),
            ),
          )
          as _i2.Client);

  @override
  _i2.Client setEndpoint(String? endPoint) =>
      (super.noSuchMethod(
            Invocation.method(#setEndpoint, [endPoint]),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#setEndpoint, [endPoint]),
            ),
          )
          as _i2.Client);

  @override
  _i2.Client setEndPointRealtime(String? endPoint) =>
      (super.noSuchMethod(
            Invocation.method(#setEndPointRealtime, [endPoint]),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#setEndPointRealtime, [endPoint]),
            ),
          )
          as _i2.Client);

  @override
  _i2.Client setProject(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setProject, [value]),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#setProject, [value]),
            ),
          )
          as _i2.Client);

  @override
  _i2.Client setJWT(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setJWT, [value]),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#setJWT, [value]),
            ),
          )
          as _i2.Client);

  @override
  _i2.Client setLocale(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLocale, [value]),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#setLocale, [value]),
            ),
          )
          as _i2.Client);

  @override
  _i2.Client setSession(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setSession, [value]),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#setSession, [value]),
            ),
          )
          as _i2.Client);

  @override
  _i2.Client setDevKey(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDevKey, [value]),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#setDevKey, [value]),
            ),
          )
          as _i2.Client);

  @override
  _i2.Client addHeader(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#addHeader, [key, value]),
            returnValue: _FakeClient_0(
              this,
              Invocation.method(#addHeader, [key, value]),
            ),
          )
          as _i2.Client);

  @override
  _i10.Future<String> ping() =>
      (super.noSuchMethod(
            Invocation.method(#ping, []),
            returnValue: _i10.Future<String>.value(
              _i17.dummyValue<String>(this, Invocation.method(#ping, [])),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<_i6.Response<dynamic>> call(
    _i19.HttpMethod? method, {
    String? path = '',
    Map<String, String>? headers = const {},
    Map<String, dynamic>? params = const {},
    _i19.ResponseType? responseType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #call,
              [method],
              {
                #path: path,
                #headers: headers,
                #params: params,
                #responseType: responseType,
              },
            ),
            returnValue: _i10.Future<_i6.Response<dynamic>>.value(
              _FakeResponse_28<dynamic>(
                this,
                Invocation.method(
                  #call,
                  [method],
                  {
                    #path: path,
                    #headers: headers,
                    #params: params,
                    #responseType: responseType,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i6.Response<dynamic>>);
}

/// A class which mocks [Realtime].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeFriends extends _i1.Mock implements _i6.Realtime {
  MockRealtimeFriends() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.RealtimeSubscription subscribe(List<String>? channels) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [channels]),
            returnValue: _FakeRealtimeSubscription_29(
              this,
              Invocation.method(#subscribe, [channels]),
            ),
          )
          as _i6.RealtimeSubscription);
}

/// A class which mocks [Realtime].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtime extends _i1.Mock implements _i6.Realtime {
  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_0(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.Client);

  @override
  _i6.RealtimeSubscription subscribe(List<String>? channels) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [channels]),
            returnValue: _FakeRealtimeSubscription_29(
              this,
              Invocation.method(#subscribe, [channels]),
            ),
            returnValueForMissingStub: _FakeRealtimeSubscription_29(
              this,
              Invocation.method(#subscribe, [channels]),
            ),
          )
          as _i6.RealtimeSubscription);
}
