// Mocks generated by Mockito 5.4.6 from annotations
// in resonate/test/controllers/upcoming_controller_tests.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:appwrite/appwrite.dart' as _i7;
import 'package:appwrite/models.dart' as _i3;
import 'package:appwrite/src/client.dart' as _i2;
import 'package:appwrite/src/realtime.dart' as _i10;
import 'package:appwrite/src/realtime_subscription.dart' as _i6;
import 'package:firebase_core/firebase_core.dart' as _i4;
import 'package:firebase_messaging/firebase_messaging.dart' as _i9;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionList_1 extends _i1.SmartFake
    implements _i3.TransactionList {
  _FakeTransactionList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_2 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRowList_3 extends _i1.SmartFake implements _i3.RowList {
  _FakeRowList_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRow_4 extends _i1.SmartFake implements _i3.Row {
  _FakeRow_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_5 extends _i1.SmartFake implements _i4.FirebaseApp {
  _FakeFirebaseApp_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettings_6 extends _i1.SmartFake
    implements _i5.NotificationSettings {
  _FakeNotificationSettings_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeSubscription_7 extends _i1.SmartFake
    implements _i6.RealtimeSubscription {
  _FakeRealtimeSubscription_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TablesDB].
///
/// See the documentation for Mockito's code generation for more information.
class MockTablesDB extends _i1.Mock implements _i7.TablesDB {
  MockTablesDB() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i8.Future<_i3.TransactionList> listTransactions({List<String>? queries}) =>
      (super.noSuchMethod(
            Invocation.method(#listTransactions, [], {#queries: queries}),
            returnValue: _i8.Future<_i3.TransactionList>.value(
              _FakeTransactionList_1(
                this,
                Invocation.method(#listTransactions, [], {#queries: queries}),
              ),
            ),
          )
          as _i8.Future<_i3.TransactionList>);

  @override
  _i8.Future<_i3.Transaction> createTransaction({int? ttl}) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {#ttl: ttl}),
            returnValue: _i8.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createTransaction, [], {#ttl: ttl}),
              ),
            ),
          )
          as _i8.Future<_i3.Transaction>);

  @override
  _i8.Future<_i3.Transaction> getTransaction({
    required String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#getTransaction, [], {
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Transaction>);

  @override
  _i8.Future<_i3.Transaction> updateTransaction({
    required String? transactionId,
    bool? commit,
    bool? rollback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [], {
              #transactionId: transactionId,
              #commit: commit,
              #rollback: rollback,
            }),
            returnValue: _i8.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#updateTransaction, [], {
                  #transactionId: transactionId,
                  #commit: commit,
                  #rollback: rollback,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Transaction>);

  @override
  _i8.Future<dynamic> deleteTransaction({required String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  _i8.Future<_i3.Transaction> createOperations({
    required String? transactionId,
    List<Map<dynamic, dynamic>>? operations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOperations, [], {
              #transactionId: transactionId,
              #operations: operations,
            }),
            returnValue: _i8.Future<_i3.Transaction>.value(
              _FakeTransaction_2(
                this,
                Invocation.method(#createOperations, [], {
                  #transactionId: transactionId,
                  #operations: operations,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Transaction>);

  @override
  _i8.Future<_i3.RowList> listRows({
    required String? databaseId,
    required String? tableId,
    List<String>? queries,
    String? transactionId,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listRows, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #queries: queries,
              #transactionId: transactionId,
              #total: total,
            }),
            returnValue: _i8.Future<_i3.RowList>.value(
              _FakeRowList_3(
                this,
                Invocation.method(#listRows, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #queries: queries,
                  #transactionId: transactionId,
                  #total: total,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.RowList>);

  @override
  _i8.Future<_i3.Row> createRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#createRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Row>);

  @override
  _i8.Future<_i3.Row> getRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    List<String>? queries,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #queries: queries,
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#getRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #queries: queries,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Row>);

  @override
  _i8.Future<_i3.Row> upsertRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#upsertRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Row>);

  @override
  _i8.Future<_i3.Row> updateRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#updateRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Row>);

  @override
  _i8.Future<dynamic> deleteRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  _i8.Future<_i3.Row> decrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? min,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #min: min,
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#decrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #min: min,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Row>);

  @override
  _i8.Future<_i3.Row> incrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? max,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #max: max,
              #transactionId: transactionId,
            }),
            returnValue: _i8.Future<_i3.Row>.value(
              _FakeRow_4(
                this,
                Invocation.method(#incrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #max: max,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.Row>);
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i9.FirebaseMessaging {
  MockFirebaseMessaging() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_5(this, Invocation.getter(#app)),
          )
          as _i4.FirebaseApp);

  @override
  bool get isAutoInitEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoInitEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i8.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i8.Stream<String>.empty(),
          )
          as _i8.Stream<String>);

  @override
  set app(_i4.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i8.Future<_i5.RemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i8.Future<_i5.RemoteMessage?>.value(),
          )
          as _i8.Future<_i5.RemoteMessage?>);

  @override
  _i8.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getAPNSToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAPNSToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> getToken({String? vapidKey}) =>
      (super.noSuchMethod(
            Invocation.method(#getToken, [], {#vapidKey: vapidKey}),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i5.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationSettings, []),
            returnValue: _i8.Future<_i5.NotificationSettings>.value(
              _FakeNotificationSettings_6(
                this,
                Invocation.method(#getNotificationSettings, []),
              ),
            ),
          )
          as _i8.Future<_i5.NotificationSettings>);

  @override
  _i8.Future<_i5.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
    bool? providesAppNotificationSettings = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, [], {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
              #providesAppNotificationSettings: providesAppNotificationSettings,
            }),
            returnValue: _i8.Future<_i5.NotificationSettings>.value(
              _FakeNotificationSettings_6(
                this,
                Invocation.method(#requestPermission, [], {
                  #alert: alert,
                  #announcement: announcement,
                  #badge: badge,
                  #carPlay: carPlay,
                  #criticalAlert: criticalAlert,
                  #provisional: provisional,
                  #sound: sound,
                  #providesAppNotificationSettings:
                      providesAppNotificationSettings,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.NotificationSettings>);

  @override
  _i8.Future<void> setAutoInitEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoInitEnabled, [enabled]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setDeliveryMetricsExportToBigQuery, [enabled]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setForegroundNotificationPresentationOptions,
              [],
              {#alert: alert, #badge: badge, #sound: sound},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [Realtime].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtime extends _i1.Mock implements _i10.Realtime {
  MockRealtime() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i6.RealtimeSubscription subscribe(List<String>? channels) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [channels]),
            returnValue: _FakeRealtimeSubscription_7(
              this,
              Invocation.method(#subscribe, [channels]),
            ),
          )
          as _i6.RealtimeSubscription);
}
