name: 📦 Dependency Update
description: Update project dependencies or address deprecation warnings
title: "DEPS: <Please write a comprehensive title after the 'DEPS: ' prefix>"

body:
  - type: markdown
    attributes:
      value: >
        Use this template for proposing dependency upgrades, security updates, or addressing deprecation warnings.

  - type: input
    id: package-name
    attributes:
      label: 📦 Package Name
      description: >
        Which package or dependency needs to be updated?
      placeholder: "appwrite"
    validations:
      required: true

  - type: input
    id: current-version
    attributes:
      label: Current Version
      description: >
        What is the current version being used?
      placeholder: "1.6.0"
    validations:
      required: true

  - type: input
    id: target-version
    attributes:
      label: Target Version
      description: >
        What version do you propose updating to?
      placeholder: "1.8.0"
    validations:
      required: true

  - type: dropdown
    id: update-reason
    attributes:
      label: Update Reason
      description: Why is this update needed?
      options:
        - "Security vulnerability fix"
        - "Deprecation warning"
        - "New features needed"
        - "Bug fix in newer version"
        - "Performance improvement"
        - "Compatibility requirement"
        - "Other"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Breaking Changes
      description: >
        Does this update include any breaking changes? If yes, describe what needs to be updated in the codebase.
      placeholder: |
        - API endpoint structure changed
        - Method signatures updated
        - Configuration format modified
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: >
        Any additional information about this dependency update? (e.g., changelog link, migration guide, testing notes)
      placeholder: |
        Changelog: https://github.com/appwrite/sdk-for-flutter/releases/tag/1.8.0
        Migration guide: https://appwrite.io/docs/migration-guide
    validations:
      required: false

  - type: markdown
    attributes:
      value: >
        Thanks for keeping Resonate's dependencies up to date! 📦
