name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature clearly.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Solution
      description: How do you propose implementing this?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Mockups, references, or examples.
