name: 🧪 Testing
description: Improve test coverage or fix testing infrastructure
title: "TEST: <Please write a comprehensive title after the 'TEST: ' prefix>"

body:
  - type: markdown
    attributes:
      value: >
        Use this template for proposing test improvements, adding new tests, or fixing test infrastructure issues.

  - type: dropdown
    id: test-type
    attributes:
      label: 🧪 Test Type
      description: What type of testing does this relate to?
      options:
        - "Unit tests"
        - "Integration tests"
        - "Widget tests"
        - "End-to-end tests"
        - "Test infrastructure"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: testing-improvement
    attributes:
      label: 🧪 The Testing Improvement
      description: >
        Describe the testing improvement you're proposing. What area of the codebase needs better test coverage or what test issues need fixing?
      placeholder: |
        Add unit tests for the authentication service to improve coverage from 45% to 80%.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: >
        Why is this testing improvement needed? What problems will it solve or prevent?
      placeholder: |
        - Current coverage is low, making refactoring risky
        - Recent bugs could have been caught by tests
        - Flaky tests are causing CI failures
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Testing Focus Areas
      description: What aspects does this improvement address?
      options:
        - label: "Increase test coverage"
        - label: "Fix flaky tests"
        - label: "Improve test performance"
        - label: "Add missing test cases"
        - label: "Update test infrastructure"
        - label: "Other"
    validations:
      required: false

  - type: markdown
    attributes:
      value: >
        Thanks for improving Resonate's test quality! 🧪
