// Mocks generated by Mockito 5.4.6 from annotations
// in resonate/test/services/api_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:appwrite/appwrite.dart' as _i4;
import 'package:appwrite/enums.dart' as _i6;
import 'package:appwrite/models.dart' as _i3;
import 'package:appwrite/src/client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExecutionList_1 extends _i1.SmartFake implements _i3.ExecutionList {
  _FakeExecutionList_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExecution_2 extends _i1.SmartFake implements _i3.Execution {
  _FakeExecution_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Functions].
///
/// See the documentation for Mockito's code generation for more information.
class MockFunctions extends _i1.Mock implements _i4.Functions {
  MockFunctions() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<_i3.ExecutionList> listExecutions({
    required String? functionId,
    List<String>? queries,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listExecutions, [], {
              #functionId: functionId,
              #queries: queries,
              #total: total,
            }),
            returnValue: _i5.Future<_i3.ExecutionList>.value(
              _FakeExecutionList_1(
                this,
                Invocation.method(#listExecutions, [], {
                  #functionId: functionId,
                  #queries: queries,
                  #total: total,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ExecutionList>);

  @override
  _i5.Future<_i3.Execution> createExecution({
    required String? functionId,
    String? body,
    bool? xasync,
    String? path,
    _i6.ExecutionMethod? method,
    Map<dynamic, dynamic>? headers,
    String? scheduledAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createExecution, [], {
              #functionId: functionId,
              #body: body,
              #xasync: xasync,
              #path: path,
              #method: method,
              #headers: headers,
              #scheduledAt: scheduledAt,
            }),
            returnValue: _i5.Future<_i3.Execution>.value(
              _FakeExecution_2(
                this,
                Invocation.method(#createExecution, [], {
                  #functionId: functionId,
                  #body: body,
                  #xasync: xasync,
                  #path: path,
                  #method: method,
                  #headers: headers,
                  #scheduledAt: scheduledAt,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Execution>);

  @override
  _i5.Future<_i3.Execution> getExecution({
    required String? functionId,
    required String? executionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExecution, [], {
              #functionId: functionId,
              #executionId: executionId,
            }),
            returnValue: _i5.Future<_i3.Execution>.value(
              _FakeExecution_2(
                this,
                Invocation.method(#getExecution, [], {
                  #functionId: functionId,
                  #executionId: executionId,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Execution>);
}
