// Mocks generated by Mockito 5.4.6 from annotations
// in resonate/test/services/room_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i15;

import 'package:appwrite/appwrite.dart' as _i2;
import 'package:appwrite/models.dart' as _i6;
import 'package:firebase_messaging/firebase_messaging.dart' as _i8;
import 'package:flutter/material.dart' as _i13;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i9;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i7;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;
import 'package:resonate/controllers/auth_state_controller.dart' as _i16;
import 'package:resonate/controllers/rooms_controller.dart' as _i12;
import 'package:resonate/models/appwrite_room.dart' as _i5;
import 'package:resonate/models/follower_user_model.dart' as _i17;
import 'package:resonate/services/api_service.dart' as _i10;
import 'package:resonate/themes/theme_controller.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFunctions_0 extends _i1.SmartFake implements _i2.Functions {
  _FakeFunctions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_1 extends _i1.SmartFake implements _i3.RxBool {
  _FakeRxBool_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClient_2 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTablesDB_3 extends _i1.SmartFake implements _i2.TablesDB {
  _FakeTablesDB_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_4<E> extends _i1.SmartFake implements _i3.RxList<E> {
  _FakeRxList_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeThemeController_5 extends _i1.SmartFake
    implements _i4.ThemeController {
  _FakeThemeController_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_6<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppwriteRoom_7 extends _i1.SmartFake implements _i5.AppwriteRoom {
  _FakeAppwriteRoom_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionList_8 extends _i1.SmartFake
    implements _i6.TransactionList {
  _FakeTransactionList_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransaction_9 extends _i1.SmartFake implements _i6.Transaction {
  _FakeTransaction_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRowList_10 extends _i1.SmartFake implements _i6.RowList {
  _FakeRowList_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRow_11 extends _i1.SmartFake implements _i6.Row {
  _FakeRow_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_12 extends _i1.SmartFake implements _i7.IOSOptions {
  _FakeIOSOptions_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_13 extends _i1.SmartFake
    implements _i7.AndroidOptions {
  _FakeAndroidOptions_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_14 extends _i1.SmartFake implements _i7.LinuxOptions {
  _FakeLinuxOptions_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_15 extends _i1.SmartFake
    implements _i7.WindowsOptions {
  _FakeWindowsOptions_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_16 extends _i1.SmartFake implements _i7.WebOptions {
  _FakeWebOptions_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_17 extends _i1.SmartFake implements _i7.MacOsOptions {
  _FakeMacOsOptions_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseMessaging_18 extends _i1.SmartFake
    implements _i8.FirebaseMessaging {
  _FakeFirebaseMessaging_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAccount_19 extends _i1.SmartFake implements _i2.Account {
  _FakeAccount_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_20 extends _i1.SmartFake implements _i6.User {
  _FakeUser_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterLocalNotificationsPlugin_21 extends _i1.SmartFake
    implements _i9.FlutterLocalNotificationsPlugin {
  _FakeFlutterLocalNotificationsPlugin_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i10.ApiService {
  @override
  _i2.Functions get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctions_0(this, Invocation.getter(#functions)),
            returnValueForMissingStub: _FakeFunctions_0(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i2.Functions);

  @override
  _i11.Future<Map<String, dynamic>> createRoom(
    String? roomName,
    String? roomDescription,
    String? adminUid,
    List<String>? roomTags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRoom, [
              roomName,
              roomDescription,
              adminUid,
              roomTags,
            ]),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<Map<String, dynamic>> joinRoom(String? roomName, String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#joinRoom, [roomName, uid]),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<Map<String, dynamic>> deleteRoom(
    String? appwriteRoomDocId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoom, [appwriteRoomDocId, token]),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<Map<String, dynamic>> createLiveChapterRoom(
    String? appwriteRoomId,
    String? adminUid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLiveChapterRoom, [
              appwriteRoomId,
              adminUid,
            ]),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<Map<String, dynamic>> deleteLiveChapterRoom(
    String? appwriteRoomDocId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLiveChapterRoom, [
              appwriteRoomDocId,
              token,
            ]),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);
}

/// A class which mocks [RoomsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoomsController extends _i1.Mock implements _i12.RoomsController {
  @override
  _i3.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isLoading)),
            returnValueForMissingStub: _FakeRxBool_1(
              this,
              Invocation.getter(#isLoading),
            ),
          )
          as _i3.RxBool);

  @override
  _i3.RxBool get isOnActive =>
      (super.noSuchMethod(
            Invocation.getter(#isOnActive),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isOnActive)),
            returnValueForMissingStub: _FakeRxBool_1(
              this,
              Invocation.getter(#isOnActive),
            ),
          )
          as _i3.RxBool);

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_2(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_2(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.Client);

  @override
  _i2.TablesDB get tablesDB =>
      (super.noSuchMethod(
            Invocation.getter(#tablesDB),
            returnValue: _FakeTablesDB_3(this, Invocation.getter(#tablesDB)),
            returnValueForMissingStub: _FakeTablesDB_3(
              this,
              Invocation.getter(#tablesDB),
            ),
          )
          as _i2.TablesDB);

  @override
  _i3.RxList<_i5.AppwriteRoom> get rooms =>
      (super.noSuchMethod(
            Invocation.getter(#rooms),
            returnValue: _FakeRxList_4<_i5.AppwriteRoom>(
              this,
              Invocation.getter(#rooms),
            ),
            returnValueForMissingStub: _FakeRxList_4<_i5.AppwriteRoom>(
              this,
              Invocation.getter(#rooms),
            ),
          )
          as _i3.RxList<_i5.AppwriteRoom>);

  @override
  _i4.ThemeController get themeController =>
      (super.noSuchMethod(
            Invocation.getter(#themeController),
            returnValue: _FakeThemeController_5(
              this,
              Invocation.getter(#themeController),
            ),
            returnValueForMissingStub: _FakeThemeController_5(
              this,
              Invocation.getter(#themeController),
            ),
          )
          as _i4.ThemeController);

  @override
  _i3.RxBool get isSearching =>
      (super.noSuchMethod(
            Invocation.getter(#isSearching),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isSearching)),
            returnValueForMissingStub: _FakeRxBool_1(
              this,
              Invocation.getter(#isSearching),
            ),
          )
          as _i3.RxBool);

  @override
  _i3.RxBool get searchBarIsEmpty =>
      (super.noSuchMethod(
            Invocation.getter(#searchBarIsEmpty),
            returnValue: _FakeRxBool_1(
              this,
              Invocation.getter(#searchBarIsEmpty),
            ),
            returnValueForMissingStub: _FakeRxBool_1(
              this,
              Invocation.getter(#searchBarIsEmpty),
            ),
          )
          as _i3.RxBool);

  @override
  _i3.RxList<_i5.AppwriteRoom> get filteredRooms =>
      (super.noSuchMethod(
            Invocation.getter(#filteredRooms),
            returnValue: _FakeRxList_4<_i5.AppwriteRoom>(
              this,
              Invocation.getter(#filteredRooms),
            ),
            returnValueForMissingStub: _FakeRxList_4<_i5.AppwriteRoom>(
              this,
              Invocation.getter(#filteredRooms),
            ),
          )
          as _i3.RxList<_i5.AppwriteRoom>);

  @override
  set isLoading(_i3.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isOnActive(_i3.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isOnActive, value),
    returnValueForMissingStub: null,
  );

  @override
  set client(_i2.Client? value) => super.noSuchMethod(
    Invocation.setter(#client, value),
    returnValueForMissingStub: null,
  );

  @override
  set rooms(_i3.RxList<_i5.AppwriteRoom>? value) => super.noSuchMethod(
    Invocation.setter(#rooms, value),
    returnValueForMissingStub: null,
  );

  @override
  set isSearching(_i3.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isSearching, value),
    returnValueForMissingStub: null,
  );

  @override
  set searchBarIsEmpty(_i3.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#searchBarIsEmpty, value),
    returnValueForMissingStub: null,
  );

  @override
  set filteredRooms(_i3.RxList<_i5.AppwriteRoom>? value) => super.noSuchMethod(
    Invocation.setter(#filteredRooms, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_6<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_6<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_6<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_6<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<_i5.AppwriteRoom> createRoomObject(
    _i6.Row? room,
    String? userUid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRoomObject, [room, userUid]),
            returnValue: _i11.Future<_i5.AppwriteRoom>.value(
              _FakeAppwriteRoom_7(
                this,
                Invocation.method(#createRoomObject, [room, userUid]),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i5.AppwriteRoom>.value(
              _FakeAppwriteRoom_7(
                this,
                Invocation.method(#createRoomObject, [room, userUid]),
              ),
            ),
          )
          as _i11.Future<_i5.AppwriteRoom>);

  @override
  _i11.Future<void> getRooms() =>
      (super.noSuchMethod(
            Invocation.method(#getRooms, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<dynamic> getRoomById(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#getRoomById, [roomId]),
            returnValue: _i11.Future<dynamic>.value(),
            returnValueForMissingStub: _i11.Future<dynamic>.value(),
          )
          as _i11.Future<dynamic>);

  @override
  _i11.Future<void> joinRoom({
    required _i5.AppwriteRoom? room,
    required _i13.BuildContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinRoom, [], {#room: room, #context: context}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> searchLiveRooms(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchLiveRooms, [query]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void clearLiveSearch() => super.noSuchMethod(
    Invocation.method(#clearLiveSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListener(_i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i14.Disposer);

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i15.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListenerId(Object? key, _i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i14.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TablesDB].
///
/// See the documentation for Mockito's code generation for more information.
class MockTablesDB extends _i1.Mock implements _i2.TablesDB {
  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_2(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_2(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.Client);

  @override
  _i11.Future<_i6.TransactionList> listTransactions({List<String>? queries}) =>
      (super.noSuchMethod(
            Invocation.method(#listTransactions, [], {#queries: queries}),
            returnValue: _i11.Future<_i6.TransactionList>.value(
              _FakeTransactionList_8(
                this,
                Invocation.method(#listTransactions, [], {#queries: queries}),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.TransactionList>.value(
              _FakeTransactionList_8(
                this,
                Invocation.method(#listTransactions, [], {#queries: queries}),
              ),
            ),
          )
          as _i11.Future<_i6.TransactionList>);

  @override
  _i11.Future<_i6.Transaction> createTransaction({int? ttl}) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [], {#ttl: ttl}),
            returnValue: _i11.Future<_i6.Transaction>.value(
              _FakeTransaction_9(
                this,
                Invocation.method(#createTransaction, [], {#ttl: ttl}),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Transaction>.value(
              _FakeTransaction_9(
                this,
                Invocation.method(#createTransaction, [], {#ttl: ttl}),
              ),
            ),
          )
          as _i11.Future<_i6.Transaction>);

  @override
  _i11.Future<_i6.Transaction> getTransaction({
    required String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<_i6.Transaction>.value(
              _FakeTransaction_9(
                this,
                Invocation.method(#getTransaction, [], {
                  #transactionId: transactionId,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Transaction>.value(
              _FakeTransaction_9(
                this,
                Invocation.method(#getTransaction, [], {
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Transaction>);

  @override
  _i11.Future<_i6.Transaction> updateTransaction({
    required String? transactionId,
    bool? commit,
    bool? rollback,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [], {
              #transactionId: transactionId,
              #commit: commit,
              #rollback: rollback,
            }),
            returnValue: _i11.Future<_i6.Transaction>.value(
              _FakeTransaction_9(
                this,
                Invocation.method(#updateTransaction, [], {
                  #transactionId: transactionId,
                  #commit: commit,
                  #rollback: rollback,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Transaction>.value(
              _FakeTransaction_9(
                this,
                Invocation.method(#updateTransaction, [], {
                  #transactionId: transactionId,
                  #commit: commit,
                  #rollback: rollback,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Transaction>);

  @override
  _i11.Future<dynamic> deleteTransaction({required String? transactionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [], {
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<dynamic>.value(),
            returnValueForMissingStub: _i11.Future<dynamic>.value(),
          )
          as _i11.Future<dynamic>);

  @override
  _i11.Future<_i6.Transaction> createOperations({
    required String? transactionId,
    List<Map<dynamic, dynamic>>? operations,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createOperations, [], {
              #transactionId: transactionId,
              #operations: operations,
            }),
            returnValue: _i11.Future<_i6.Transaction>.value(
              _FakeTransaction_9(
                this,
                Invocation.method(#createOperations, [], {
                  #transactionId: transactionId,
                  #operations: operations,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Transaction>.value(
              _FakeTransaction_9(
                this,
                Invocation.method(#createOperations, [], {
                  #transactionId: transactionId,
                  #operations: operations,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Transaction>);

  @override
  _i11.Future<_i6.RowList> listRows({
    required String? databaseId,
    required String? tableId,
    List<String>? queries,
    String? transactionId,
    bool? total,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listRows, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #queries: queries,
              #transactionId: transactionId,
              #total: total,
            }),
            returnValue: _i11.Future<_i6.RowList>.value(
              _FakeRowList_10(
                this,
                Invocation.method(#listRows, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #queries: queries,
                  #transactionId: transactionId,
                  #total: total,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.RowList>.value(
              _FakeRowList_10(
                this,
                Invocation.method(#listRows, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #queries: queries,
                  #transactionId: transactionId,
                  #total: total,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.RowList>);

  @override
  _i11.Future<_i6.Row> createRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#createRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#createRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Row>);

  @override
  _i11.Future<_i6.Row> getRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    List<String>? queries,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #queries: queries,
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#getRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #queries: queries,
                  #transactionId: transactionId,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#getRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #queries: queries,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Row>);

  @override
  _i11.Future<_i6.Row> upsertRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#upsertRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#upsertRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Row>);

  @override
  _i11.Future<_i6.Row> updateRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    Map<dynamic, dynamic>? data,
    List<String>? permissions,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #data: data,
              #permissions: permissions,
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#updateRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#updateRow, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #data: data,
                  #permissions: permissions,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Row>);

  @override
  _i11.Future<dynamic> deleteRow({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRow, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<dynamic>.value(),
            returnValueForMissingStub: _i11.Future<dynamic>.value(),
          )
          as _i11.Future<dynamic>);

  @override
  _i11.Future<_i6.Row> decrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? min,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#decrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #min: min,
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#decrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #min: min,
                  #transactionId: transactionId,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#decrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #min: min,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Row>);

  @override
  _i11.Future<_i6.Row> incrementRowColumn({
    required String? databaseId,
    required String? tableId,
    required String? rowId,
    required String? column,
    double? value,
    double? max,
    String? transactionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRowColumn, [], {
              #databaseId: databaseId,
              #tableId: tableId,
              #rowId: rowId,
              #column: column,
              #value: value,
              #max: max,
              #transactionId: transactionId,
            }),
            returnValue: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#incrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #max: max,
                  #transactionId: transactionId,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i6.Row>.value(
              _FakeRow_11(
                this,
                Invocation.method(#incrementRowColumn, [], {
                  #databaseId: databaseId,
                  #tableId: tableId,
                  #rowId: rowId,
                  #column: column,
                  #value: value,
                  #max: max,
                  #transactionId: transactionId,
                }),
              ),
            ),
          )
          as _i11.Future<_i6.Row>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i7.FlutterSecureStorage {
  @override
  _i7.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_12(this, Invocation.getter(#iOptions)),
            returnValueForMissingStub: _FakeIOSOptions_12(
              this,
              Invocation.getter(#iOptions),
            ),
          )
          as _i7.IOSOptions);

  @override
  _i7.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_13(
              this,
              Invocation.getter(#aOptions),
            ),
            returnValueForMissingStub: _FakeAndroidOptions_13(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i7.AndroidOptions);

  @override
  _i7.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_14(
              this,
              Invocation.getter(#lOptions),
            ),
            returnValueForMissingStub: _FakeLinuxOptions_14(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i7.LinuxOptions);

  @override
  _i7.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_15(
              this,
              Invocation.getter(#wOptions),
            ),
            returnValueForMissingStub: _FakeWindowsOptions_15(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i7.WindowsOptions);

  @override
  _i7.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_16(
              this,
              Invocation.getter(#webOptions),
            ),
            returnValueForMissingStub: _FakeWebOptions_16(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i7.WebOptions);

  @override
  _i7.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_17(
              this,
              Invocation.getter(#mOptions),
            ),
            returnValueForMissingStub: _FakeMacOsOptions_17(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i7.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i13.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i13.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> write({
    required String? key,
    required String? value,
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<String?> read({
    required String? key,
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<String?>.value(),
            returnValueForMissingStub: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<bool> containsKey({
    required String? key,
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<void> delete({
    required String? key,
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<Map<String, String>> readAll({
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<Map<String, String>>.value(
              <String, String>{},
            ),
            returnValueForMissingStub: _i11.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i11.Future<Map<String, String>>);

  @override
  _i11.Future<void> deleteAll({
    _i7.IOSOptions? iOptions,
    _i7.AndroidOptions? aOptions,
    _i7.LinuxOptions? lOptions,
    _i7.WebOptions? webOptions,
    _i7.MacOsOptions? mOptions,
    _i7.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i11.Future<bool?>.value(),
            returnValueForMissingStub: _i11.Future<bool?>.value(),
          )
          as _i11.Future<bool?>);
}

/// A class which mocks [AuthStateController].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStateController extends _i1.Mock
    implements _i16.AuthStateController {
  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_2(this, Invocation.getter(#client)),
            returnValueForMissingStub: _FakeClient_2(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.Client);

  @override
  _i2.TablesDB get tables =>
      (super.noSuchMethod(
            Invocation.getter(#tables),
            returnValue: _FakeTablesDB_3(this, Invocation.getter(#tables)),
            returnValueForMissingStub: _FakeTablesDB_3(
              this,
              Invocation.getter(#tables),
            ),
          )
          as _i2.TablesDB);

  @override
  _i3.RxBool get isInitializing =>
      (super.noSuchMethod(
            Invocation.getter(#isInitializing),
            returnValue: _FakeRxBool_1(
              this,
              Invocation.getter(#isInitializing),
            ),
            returnValueForMissingStub: _FakeRxBool_1(
              this,
              Invocation.getter(#isInitializing),
            ),
          )
          as _i3.RxBool);

  @override
  _i8.FirebaseMessaging get messaging =>
      (super.noSuchMethod(
            Invocation.getter(#messaging),
            returnValue: _FakeFirebaseMessaging_18(
              this,
              Invocation.getter(#messaging),
            ),
            returnValueForMissingStub: _FakeFirebaseMessaging_18(
              this,
              Invocation.getter(#messaging),
            ),
          )
          as _i8.FirebaseMessaging);

  @override
  _i2.Account get account =>
      (super.noSuchMethod(
            Invocation.getter(#account),
            returnValue: _FakeAccount_19(this, Invocation.getter(#account)),
            returnValueForMissingStub: _FakeAccount_19(
              this,
              Invocation.getter(#account),
            ),
          )
          as _i2.Account);

  @override
  double get ratingTotal =>
      (super.noSuchMethod(
            Invocation.getter(#ratingTotal),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  int get ratingCount =>
      (super.noSuchMethod(
            Invocation.getter(#ratingCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i6.User get appwriteUser =>
      (super.noSuchMethod(
            Invocation.getter(#appwriteUser),
            returnValue: _FakeUser_20(this, Invocation.getter(#appwriteUser)),
            returnValueForMissingStub: _FakeUser_20(
              this,
              Invocation.getter(#appwriteUser),
            ),
          )
          as _i6.User);

  @override
  List<_i17.FollowerUserModel> get followerDocuments =>
      (super.noSuchMethod(
            Invocation.getter(#followerDocuments),
            returnValue: <_i17.FollowerUserModel>[],
            returnValueForMissingStub: <_i17.FollowerUserModel>[],
          )
          as List<_i17.FollowerUserModel>);

  @override
  int get reportsCount =>
      (super.noSuchMethod(
            Invocation.getter(#reportsCount),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i9.FlutterLocalNotificationsPlugin get flutterLocalNotificationsPlugin =>
      (super.noSuchMethod(
            Invocation.getter(#flutterLocalNotificationsPlugin),
            returnValue: _FakeFlutterLocalNotificationsPlugin_21(
              this,
              Invocation.getter(#flutterLocalNotificationsPlugin),
            ),
            returnValueForMissingStub: _FakeFlutterLocalNotificationsPlugin_21(
              this,
              Invocation.getter(#flutterLocalNotificationsPlugin),
            ),
          )
          as _i9.FlutterLocalNotificationsPlugin);

  @override
  _i11.Future<bool> get getLoginState =>
      (super.noSuchMethod(
            Invocation.getter(#getLoginState),
            returnValue: _i11.Future<bool>.value(false),
            returnValueForMissingStub: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  set client(_i2.Client? value) => super.noSuchMethod(
    Invocation.setter(#client, value),
    returnValueForMissingStub: null,
  );

  @override
  set isInitializing(_i3.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isInitializing, value),
    returnValueForMissingStub: null,
  );

  @override
  set messaging(_i8.FirebaseMessaging? value) => super.noSuchMethod(
    Invocation.setter(#messaging, value),
    returnValueForMissingStub: null,
  );

  @override
  set account(_i2.Account? value) => super.noSuchMethod(
    Invocation.setter(#account, value),
    returnValueForMissingStub: null,
  );

  @override
  set uid(String? value) => super.noSuchMethod(
    Invocation.setter(#uid, value),
    returnValueForMissingStub: null,
  );

  @override
  set profileImageID(String? value) => super.noSuchMethod(
    Invocation.setter(#profileImageID, value),
    returnValueForMissingStub: null,
  );

  @override
  set displayName(String? value) => super.noSuchMethod(
    Invocation.setter(#displayName, value),
    returnValueForMissingStub: null,
  );

  @override
  set email(String? value) => super.noSuchMethod(
    Invocation.setter(#email, value),
    returnValueForMissingStub: null,
  );

  @override
  set profileImageUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#profileImageUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set userName(String? value) => super.noSuchMethod(
    Invocation.setter(#userName, value),
    returnValueForMissingStub: null,
  );

  @override
  set isUserProfileComplete(bool? value) => super.noSuchMethod(
    Invocation.setter(#isUserProfileComplete, value),
    returnValueForMissingStub: null,
  );

  @override
  set isEmailVerified(bool? value) => super.noSuchMethod(
    Invocation.setter(#isEmailVerified, value),
    returnValueForMissingStub: null,
  );

  @override
  set ratingTotal(double? value) => super.noSuchMethod(
    Invocation.setter(#ratingTotal, value),
    returnValueForMissingStub: null,
  );

  @override
  set ratingCount(int? value) => super.noSuchMethod(
    Invocation.setter(#ratingCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set appwriteUser(_i6.User? value) => super.noSuchMethod(
    Invocation.setter(#appwriteUser, value),
    returnValueForMissingStub: null,
  );

  @override
  set followerDocuments(List<_i17.FollowerUserModel>? value) =>
      super.noSuchMethod(
        Invocation.setter(#followerDocuments, value),
        returnValueForMissingStub: null,
      );

  @override
  set reportsCount(int? value) => super.noSuchMethod(
    Invocation.setter(#reportsCount, value),
    returnValueForMissingStub: null,
  );

  @override
  set flutterLocalNotificationsPlugin(
    _i9.FlutterLocalNotificationsPlugin? value,
  ) => super.noSuchMethod(
    Invocation.setter(#flutterLocalNotificationsPlugin, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_6<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_6<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_6<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_6<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i11.Future<void> initializeLocalNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#initializeLocalNotifications, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void onDidReceiveNotificationResponse(
    _i9.NotificationResponse? notificationResponse,
  ) => super.noSuchMethod(
    Invocation.method(#onDidReceiveNotificationResponse, [
      notificationResponse,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> setUserProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#setUserProfileData, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> isUserLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isUserLoggedIn, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> addRegistrationTokentoSubscribedandCreatedUpcomingRooms() =>
      (super.noSuchMethod(
            Invocation.method(
              #addRegistrationTokentoSubscribedandCreatedUpcomingRooms,
              [],
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> removeRegistrationTokenFromSubscribedUpcomingRooms() =>
      (super.noSuchMethod(
            Invocation.method(
              #removeRegistrationTokenFromSubscribedUpcomingRooms,
              [],
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> signup(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [email, password]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> loginWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> loginWithGithub() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGithub, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> logout(_i13.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [context]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListener(_i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i14.Disposer);

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i15.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Disposer addListenerId(Object? key, _i14.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i14.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
