//import required packages
// ignore: depend_on_referenced_packages
import 'package:freezed_annotation/freezed_annotation.dart'; // This import allows the use of @freezed

//part files where generated code for freezed class will be placed.
part 'resonate_user.freezed.dart';
part 'resonate_user.g.dart';

@freezed
class ResonateUser with _$ResonateUser {
  //_$ResonateUser is a mixin generated by freezed package

  //create a factory constructor for ResonateUser.
  //this factory constructor is used to create instance of ResonateUser
  const factory ResonateUser({
    String? uid,
    String? userName,
    String? profileImageUrl,
    String? gender,
    String? dateOfBirth,
  }) = _ResonateUser;

  //factory method that uses _$ResonateUserFromJson from the generated code.
  factory ResonateUser.fromJson(Map<String, dynamic> json) =>
      _$ResonateUserFromJson(json);
}
